=begin comment

CoinAPI Indexes REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Contact: support@apibricks.io
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::IndexInputDataApi');

my $api = WWW::OpenAPIClient::IndexInputDataApi->new();
isa_ok($api, 'WWW::OpenAPIClient::IndexInputDataApi');

#
# v1_indexdef_input_data_index_definition_id_all_get test
#
# uncomment below and update the test
#my $v1_indexdef_input_data_index_definition_id_all_get_index_definition_id = undef; # replace NULL with a proper value
#my $v1_indexdef_input_data_index_definition_id_all_get_result = $api->v1_indexdef_input_data_index_definition_id_all_get(index_definition_id => $v1_indexdef_input_data_index_definition_id_all_get_index_definition_id);

#
# v1_indexdef_input_data_index_definition_id_get test
#
# uncomment below and update the test
#my $v1_indexdef_input_data_index_definition_id_get_index_definition_id = undef; # replace NULL with a proper value
#my $v1_indexdef_input_data_index_definition_id_get_time = undef; # replace NULL with a proper value
#my $v1_indexdef_input_data_index_definition_id_get_enabled_only = undef; # replace NULL with a proper value
#my $v1_indexdef_input_data_index_definition_id_get_pending_only = undef; # replace NULL with a proper value
#my $v1_indexdef_input_data_index_definition_id_get_filter_asset_id = undef; # replace NULL with a proper value
#my $v1_indexdef_input_data_index_definition_id_get_with_status_info = undef; # replace NULL with a proper value
#my $v1_indexdef_input_data_index_definition_id_get_result = $api->v1_indexdef_input_data_index_definition_id_get(index_definition_id => $v1_indexdef_input_data_index_definition_id_get_index_definition_id, time => $v1_indexdef_input_data_index_definition_id_get_time, enabled_only => $v1_indexdef_input_data_index_definition_id_get_enabled_only, pending_only => $v1_indexdef_input_data_index_definition_id_get_pending_only, filter_asset_id => $v1_indexdef_input_data_index_definition_id_get_filter_asset_id, with_status_info => $v1_indexdef_input_data_index_definition_id_get_with_status_info);


done_testing();
