/*
 * FinFeedAPI Stock REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using APIBricks.FinFeedAPI.STOCKAPI.REST.V1.Model;
using APIBricks.FinFeedAPI.STOCKAPI.REST.V1.Client;
using System.Reflection;

namespace APIBricks.FinFeedAPI.STOCKAPI.REST.V1.Test.Model
{
    /// <summary>
    ///  Class for testing ModelsOrderBookModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ModelsOrderBookModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ModelsOrderBookModel
        //private ModelsOrderBookModel instance;

        public ModelsOrderBookModelTests()
        {
            // TODO uncomment below to create an instance of ModelsOrderBookModel
            //instance = new ModelsOrderBookModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ModelsOrderBookModel
        /// </summary>
        [Fact]
        public void ModelsOrderBookModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" ModelsOrderBookModel
            //Assert.IsType<ModelsOrderBookModel>(instance);
        }

        /// <summary>
        /// Test the property 'AddOrder'
        /// </summary>
        [Fact]
        public void AddOrderTest()
        {
            // TODO unit test for the property 'AddOrder'
        }

        /// <summary>
        /// Test the property 'DeleteOrder'
        /// </summary>
        [Fact]
        public void DeleteOrderTest()
        {
            // TODO unit test for the property 'DeleteOrder'
        }

        /// <summary>
        /// Test the property 'ModifyOrder'
        /// </summary>
        [Fact]
        public void ModifyOrderTest()
        {
            // TODO unit test for the property 'ModifyOrder'
        }

        /// <summary>
        /// Test the property 'ExecutedOrder'
        /// </summary>
        [Fact]
        public void ExecutedOrderTest()
        {
            // TODO unit test for the property 'ExecutedOrder'
        }

        /// <summary>
        /// Test the property 'ClearBook'
        /// </summary>
        [Fact]
        public void ClearBookTest()
        {
            // TODO unit test for the property 'ClearBook'
        }
    }
}
