/*
 * FinFeedAPI Stock REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using APIBricks.FinFeedAPI.STOCKAPI.REST.V1.Model;
using APIBricks.FinFeedAPI.STOCKAPI.REST.V1.Client;
using System.Reflection;

namespace APIBricks.FinFeedAPI.STOCKAPI.REST.V1.Test.Model
{
    /// <summary>
    ///  Class for testing ModelsOperationalHaltStatusModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ModelsOperationalHaltStatusModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ModelsOperationalHaltStatusModel
        //private ModelsOperationalHaltStatusModel instance;

        public ModelsOperationalHaltStatusModelTests()
        {
            // TODO uncomment below to create an instance of ModelsOperationalHaltStatusModel
            //instance = new ModelsOperationalHaltStatusModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ModelsOperationalHaltStatusModel
        /// </summary>
        [Fact]
        public void ModelsOperationalHaltStatusModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" ModelsOperationalHaltStatusModel
            //Assert.IsType<ModelsOperationalHaltStatusModel>(instance);
        }

        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Fact]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }

        /// <summary>
        /// Test the property 'TimestampNanos'
        /// </summary>
        [Fact]
        public void TimestampNanosTest()
        {
            // TODO unit test for the property 'TimestampNanos'
        }

        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Fact]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }

        /// <summary>
        /// Test the property 'OperationalHaltStatus'
        /// </summary>
        [Fact]
        public void OperationalHaltStatusTest()
        {
            // TODO unit test for the property 'OperationalHaltStatus'
        }

        /// <summary>
        /// Test the property 'OperationalHaltStatusCode'
        /// </summary>
        [Fact]
        public void OperationalHaltStatusCodeTest()
        {
            // TODO unit test for the property 'OperationalHaltStatusCode'
        }

        /// <summary>
        /// Test the property 'OperationalHaltStatusText'
        /// </summary>
        [Fact]
        public void OperationalHaltStatusTextTest()
        {
            // TODO unit test for the property 'OperationalHaltStatusText'
        }

        /// <summary>
        /// Test the property 'IsOperationallyHalted'
        /// </summary>
        [Fact]
        public void IsOperationallyHaltedTest()
        {
            // TODO unit test for the property 'IsOperationallyHalted'
        }

        /// <summary>
        /// Test the property 'IsNotOperationallyHalted'
        /// </summary>
        [Fact]
        public void IsNotOperationallyHaltedTest()
        {
            // TODO unit test for the property 'IsNotOperationallyHalted'
        }
    }
}
