/*
 * FinFeedAPI Stock REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using APIBricks.FinFeedAPI.STOCKAPI.REST.V1.Model;
using APIBricks.FinFeedAPI.STOCKAPI.REST.V1.Client;
using System.Reflection;

namespace APIBricks.FinFeedAPI.STOCKAPI.REST.V1.Test.Model
{
    /// <summary>
    ///  Class for testing ModelsRetailLiquidityIndicatorModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ModelsRetailLiquidityIndicatorModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ModelsRetailLiquidityIndicatorModel
        //private ModelsRetailLiquidityIndicatorModel instance;

        public ModelsRetailLiquidityIndicatorModelTests()
        {
            // TODO uncomment below to create an instance of ModelsRetailLiquidityIndicatorModel
            //instance = new ModelsRetailLiquidityIndicatorModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ModelsRetailLiquidityIndicatorModel
        /// </summary>
        [Fact]
        public void ModelsRetailLiquidityIndicatorModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" ModelsRetailLiquidityIndicatorModel
            //Assert.IsType<ModelsRetailLiquidityIndicatorModel>(instance);
        }

        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Fact]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }

        /// <summary>
        /// Test the property 'TimestampNanos'
        /// </summary>
        [Fact]
        public void TimestampNanosTest()
        {
            // TODO unit test for the property 'TimestampNanos'
        }

        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Fact]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }

        /// <summary>
        /// Test the property 'RetailLiquidityIndicator'
        /// </summary>
        [Fact]
        public void RetailLiquidityIndicatorTest()
        {
            // TODO unit test for the property 'RetailLiquidityIndicator'
        }

        /// <summary>
        /// Test the property 'RetailLiquidityIndicatorCode'
        /// </summary>
        [Fact]
        public void RetailLiquidityIndicatorCodeTest()
        {
            // TODO unit test for the property 'RetailLiquidityIndicatorCode'
        }

        /// <summary>
        /// Test the property 'RetailLiquidityIndicatorText'
        /// </summary>
        [Fact]
        public void RetailLiquidityIndicatorTextTest()
        {
            // TODO unit test for the property 'RetailLiquidityIndicatorText'
        }

        /// <summary>
        /// Test the property 'IsRetailIndicatorNotApplicable'
        /// </summary>
        [Fact]
        public void IsRetailIndicatorNotApplicableTest()
        {
            // TODO unit test for the property 'IsRetailIndicatorNotApplicable'
        }

        /// <summary>
        /// Test the property 'IsRetailIndicatorBuyInterest'
        /// </summary>
        [Fact]
        public void IsRetailIndicatorBuyInterestTest()
        {
            // TODO unit test for the property 'IsRetailIndicatorBuyInterest'
        }

        /// <summary>
        /// Test the property 'IsRetailIndicatorSellInterest'
        /// </summary>
        [Fact]
        public void IsRetailIndicatorSellInterestTest()
        {
            // TODO unit test for the property 'IsRetailIndicatorSellInterest'
        }

        /// <summary>
        /// Test the property 'IsRetailIndicatorBuyAndSellInterest'
        /// </summary>
        [Fact]
        public void IsRetailIndicatorBuyAndSellInterestTest()
        {
            // TODO unit test for the property 'IsRetailIndicatorBuyAndSellInterest'
        }
    }
}
