/**
 * CoinAPI Indexes REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.21.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/Models_IndexIdentifier.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Models_IndexIdentifier::Models_IndexIdentifier()
{
}

Models_IndexIdentifier::~Models_IndexIdentifier()
{
}

void Models_IndexIdentifier::validate()
{
    // TODO: implement validation
}

web::json::value Models_IndexIdentifier::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Id.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id.get());
    }

    return val;
}

bool Models_IndexIdentifier::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    return ok;
}

void Models_IndexIdentifier::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Id.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id.get()));
    }
}

bool Models_IndexIdentifier::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        utility::string_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    return ok;
}


utility::string_t Models_IndexIdentifier::getId() const
{
    return m_Id.get();
}


void Models_IndexIdentifier::setId(const utility::string_t& value)
{
    m_Id = value;
}

bool Models_IndexIdentifier::idIsSet() const
{
    return m_Id.has_value();
}

void Models_IndexIdentifier::unsetId()
{
    m_Id.reset();
}

}
}
}
}


