/**
 * CoinAPI Indexes REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.20.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/Models_IndexValue.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Models_IndexValue::Models_IndexValue()
{
    m_Timestamp = utility::datetime();
    m_TimestampIsSet = false;
    m_Value = 0.0;
    m_ValueIsSet = false;
}

Models_IndexValue::~Models_IndexValue()
{
}

void Models_IndexValue::validate()
{
    // TODO: implement validation
}

web::json::value Models_IndexValue::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_TimestampIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("timestamp"))] = ModelBase::toJson(m_Timestamp);
    }
    if(m_ValueIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("value"))] = ModelBase::toJson(m_Value);
    }
    if(m_Composition.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("composition"))] = ModelBase::toJson(m_Composition.get());
    }

    return val;
}

bool Models_IndexValue::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("timestamp"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("timestamp")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setTimestamp;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTimestamp);
            setTimestamp(refVal_setTimestamp);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("value"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("value")));
        if(!fieldValue.is_null())
        {
            double refVal_setValue;
            ok &= ModelBase::fromJson(fieldValue, refVal_setValue);
            setValue(refVal_setValue);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("composition"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("composition")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Models_IndexValueComponent>> refVal_setComposition;
            ok &= ModelBase::fromJson(fieldValue, refVal_setComposition);
            setComposition(refVal_setComposition);
            
        }
    }
    return ok;
}

void Models_IndexValue::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_TimestampIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("timestamp")), m_Timestamp));
    }
    if(m_ValueIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("value")), m_Value));
    }
    if(m_Composition.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("composition")), m_Composition.get()));
    }
}

bool Models_IndexValue::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("timestamp"))))
    {
        utility::datetime refVal_setTimestamp;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("timestamp"))), refVal_setTimestamp );
        setTimestamp(refVal_setTimestamp);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("value"))))
    {
        double refVal_setValue;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("value"))), refVal_setValue );
        setValue(refVal_setValue);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("composition"))))
    {
        std::vector<std::shared_ptr<Models_IndexValueComponent>> refVal_setComposition;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("composition"))), refVal_setComposition );
        setComposition(refVal_setComposition);
    }
    return ok;
}


utility::datetime Models_IndexValue::getTimestamp() const
{
    return m_Timestamp;
}


void Models_IndexValue::setTimestamp(const utility::datetime& value)
{
    m_Timestamp = value;
    m_TimestampIsSet = true;
}

bool Models_IndexValue::timestampIsSet() const
{
    return m_TimestampIsSet;
}

void Models_IndexValue::unsetTimestamp()
{
    m_TimestampIsSet = false;
}
double Models_IndexValue::getValue() const
{
    return m_Value;
}

void Models_IndexValue::setValue(double value)
{
    m_Value = value;
    m_ValueIsSet = true;
}

bool Models_IndexValue::valueIsSet() const
{
    return m_ValueIsSet;
}

void Models_IndexValue::unsetValue()
{
    m_ValueIsSet = false;
}
std::vector<std::shared_ptr<Models_IndexValueComponent>> Models_IndexValue::getComposition() const
{
    return m_Composition.get();
}


void Models_IndexValue::setComposition(const std::vector<std::shared_ptr<Models_IndexValueComponent>>& value)
{
    m_Composition = value;
}

bool Models_IndexValue::compositionIsSet() const
{
    return m_Composition.has_value();
}

void Models_IndexValue::unsetComposition()
{
    m_Composition.reset();
}

}
}
}
}


