/**
 * CoinAPI Indexes REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.20.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/Models_IndexValueComponent.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Models_IndexValueComponent::Models_IndexValueComponent()
{
    m_Component_value = 0.0;
    m_Component_valueIsSet = false;
}

Models_IndexValueComponent::~Models_IndexValueComponent()
{
}

void Models_IndexValueComponent::validate()
{
    // TODO: implement validation
}

web::json::value Models_IndexValueComponent::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Component_id.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("component_id"))] = ModelBase::toJson(m_Component_id.get());
    }
    if(m_Component_valueIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("component_value"))] = ModelBase::toJson(m_Component_value);
    }

    return val;
}

bool Models_IndexValueComponent::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("component_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("component_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setComponentId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setComponentId);
            setComponentId(refVal_setComponentId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("component_value"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("component_value")));
        if(!fieldValue.is_null())
        {
            double refVal_setComponentValue;
            ok &= ModelBase::fromJson(fieldValue, refVal_setComponentValue);
            setComponentValue(refVal_setComponentValue);
            
        }
    }
    return ok;
}

void Models_IndexValueComponent::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Component_id.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("component_id")), m_Component_id.get()));
    }
    if(m_Component_valueIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("component_value")), m_Component_value));
    }
}

bool Models_IndexValueComponent::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("component_id"))))
    {
        utility::string_t refVal_setComponentId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("component_id"))), refVal_setComponentId );
        setComponentId(refVal_setComponentId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("component_value"))))
    {
        double refVal_setComponentValue;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("component_value"))), refVal_setComponentValue );
        setComponentValue(refVal_setComponentValue);
    }
    return ok;
}


utility::string_t Models_IndexValueComponent::getComponentId() const
{
    return m_Component_id.get();
}


void Models_IndexValueComponent::setComponentId(const utility::string_t& value)
{
    m_Component_id = value;
}

bool Models_IndexValueComponent::componentIdIsSet() const
{
    return m_Component_id.has_value();
}

void Models_IndexValueComponent::unsetComponent_id()
{
    m_Component_id.reset();
}
double Models_IndexValueComponent::getComponentValue() const
{
    return m_Component_value;
}

void Models_IndexValueComponent::setComponentValue(double value)
{
    m_Component_value = value;
    m_Component_valueIsSet = true;
}

bool Models_IndexValueComponent::componentValueIsSet() const
{
    return m_Component_valueIsSet;
}

void Models_IndexValueComponent::unsetComponent_value()
{
    m_Component_valueIsSet = false;
}

}
}
}
}


