/**
 * CoinAPI Indexes REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.21.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * IndexInputDataApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_IndexInputDataApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_IndexInputDataApi_H_



#include "CppRestOpenAPIClient/ApiClient.h"

#include "CppRestOpenAPIClient/model/Models_IndexDefinitionInputData.h"
#include "CppRestOpenAPIClient/model/Models_IndexDefinitionSnapshotEntry.h"
#include <vector>
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  IndexInputDataApi 
{
public:

    explicit IndexInputDataApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~IndexInputDataApi();

    /// <summary>
    /// Returns all data inputs for a specific index definition
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="indexDefinitionId"></param>
    pplx::task<std::vector<std::shared_ptr<Models_IndexDefinitionInputData>>> v1IndexdefInputDataIndexDefinitionIdAllGet(
        utility::string_t indexDefinitionId
    ) const;
    /// <summary>
    /// Returns data inputs for certain index definition and time
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="indexDefinitionId"></param>
    /// <param name="time"> (optional, default to utility::datetime())</param>
    /// <param name="enabledOnly"> (optional, default to false)</param>
    /// <param name="pendingOnly"> (optional, default to false)</param>
    /// <param name="filterAssetId"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="withStatusInfo"> (optional, default to false)</param>
    pplx::task<std::vector<std::shared_ptr<Models_IndexDefinitionSnapshotEntry>>> v1IndexdefInputDataIndexDefinitionIdGet(
        utility::string_t indexDefinitionId,
        boost::optional<utility::datetime> time,
        boost::optional<bool> enabledOnly,
        boost::optional<bool> pendingOnly,
        boost::optional<utility::string_t> filterAssetId,
        boost::optional<bool> withStatusInfo
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_IndexInputDataApi_H_ */

