#
# FinFeedAPI Stock REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Contact: support@apibricks.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ModelsAddOrderModel' {
    Context 'ModelsAddOrderModel' {
        It 'Initialize-ModelsAddOrderModel' {
            # a simple test to create an object
            #$NewObject = Initialize-ModelsAddOrderModel -Symbol "TEST_VALUE" -TimestampNanos "TEST_VALUE" -Timestamp "TEST_VALUE" -IsSideBuy "TEST_VALUE" -Size "TEST_VALUE" -Price "TEST_VALUE" -OrderId "TEST_VALUE"
            #$NewObject | Should -BeOfType ModelsAddOrderModel
            #$NewObject.property | Should -Be 0
        }
    }
}
