=begin comment

Exchange Rates Realtime REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Contact: support@apibricks.io
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::RateLimitApi');

my $api = WWW::OpenAPIClient::RateLimitApi->new();
isa_ok($api, 'WWW::OpenAPIClient::RateLimitApi');

#
# internal_ratelimit_wsconcon_apikey_get test
#
# uncomment below and update the test
#my $internal_ratelimit_wsconcon_apikey_get_result = $api->internal_ratelimit_wsconcon_apikey_get();

#
# internal_ratelimit_wshello_ip_get test
#
# uncomment below and update the test
#my $internal_ratelimit_wshello_ip_get_result = $api->internal_ratelimit_wshello_ip_get();

#
# internal_ratelimit_wsreq_ip_get test
#
# uncomment below and update the test
#my $internal_ratelimit_wsreq_ip_get_result = $api->internal_ratelimit_wsreq_ip_get();


done_testing();
