// tslint:disable
/**
 * CoinAPI Market Data REST API
 * Cryptocurrency market data: metadata, quotes, books, trades, OHLCV, rates, metrics, options.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    V1QuoteTrade,
} from './';

/**
 * Represents a strike within the option exchange group.
 * @export
 * @interface OptionsStrike
 */
export interface OptionsStrike {
    /**
     * The strike price.
     * @type {number}
     * @memberof OptionsStrike
     */
    strike_price?: number;
    /**
     * @type {V1QuoteTrade}
     * @memberof OptionsStrike
     */
    call?: V1QuoteTrade;
    /**
     * @type {V1QuoteTrade}
     * @memberof OptionsStrike
     */
    put?: V1QuoteTrade;
}
