// tslint:disable
/**
 * CoinAPI Market Data REST API
 * Cryptocurrency market data: metadata, quotes, books, trades, OHLCV, rates, metrics, options.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents a listing data item.
 * @export
 * @interface V1ListingItem
 */
export interface V1ListingItem {
    /**
     * Gets or sets the metric ID.
     * @type {string}
     * @memberof V1ListingItem
     */
    metric_id?: string | null;
    /**
     * Gets or sets the CoinAPI symbol ID. Null for exchange-level metrics.
     * @type {string}
     * @memberof V1ListingItem
     */
    symbol_id?: string | null;
    /**
     * Gets or sets the exchange-native symbol ID. Null for exchange-level metrics.
     * @type {string}
     * @memberof V1ListingItem
     */
    symbol_id_external?: string | null;
    /**
     * Gets or sets the exchange ID.
     * @type {string}
     * @memberof V1ListingItem
     */
    exchange_id?: string | null;
    /**
     * Gets or sets the asset ID.
     * @type {string}
     * @memberof V1ListingItem
     */
    asset_id?: string | null;
    /**
     * Gets or sets the asset ID.
     * @type {string}
     * @memberof V1ListingItem
     */
    asset_id_external?: string | null;
    /**
     * Gets or sets the chain ID.
     * @type {string}
     * @memberof V1ListingItem
     */
    chain_id?: string | null;
    /**
     * Gets or sets the network ID.
     * @type {string}
     * @memberof V1ListingItem
     */
    network_id?: string | null;
}
