// tslint:disable
/**
 * CoinAPI Market Data REST API
 * Cryptocurrency market data: metadata, quotes, books, trades, OHLCV, rates, metrics, options.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents the depth of an order book.
 * @export
 * @interface V1OrderBookDepth
 */
export interface V1OrderBookDepth {
    /**
     * Gets or sets the symbol identifier.
     * @type {string}
     * @memberof V1OrderBookDepth
     */
    symbol_id?: string | null;
    /**
     * Gets or sets the exchange time of the order book.
     * @type {string}
     * @memberof V1OrderBookDepth
     */
    time_exchange?: string;
    /**
     * Gets or sets the CoinAPI time when the order book was received.
     * @type {string}
     * @memberof V1OrderBookDepth
     */
    time_coinapi?: string;
    /**
     * Gets or sets the number of ask levels in the order book.
     * @type {number}
     * @memberof V1OrderBookDepth
     */
    ask_levels?: number;
    /**
     * Gets or sets the number of bid levels in the order book.
     * @type {number}
     * @memberof V1OrderBookDepth
     */
    bid_levels?: number;
    /**
     * Gets or sets the depth of the ask side of the order book.
     * @type {number}
     * @memberof V1OrderBookDepth
     */
    ask_depth?: number;
    /**
     * Gets or sets the depth of the bid side of the order book.
     * @type {number}
     * @memberof V1OrderBookDepth
     */
    bid_depth?: number;
}
