// tslint:disable
/**
 * CoinAPI Market Data REST API
 * Cryptocurrency market data: metadata, quotes, books, trades, OHLCV, rates, metrics, options.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents a symbol data model.
 * @export
 * @interface V1Symbol
 */
export interface V1Symbol {
    /**
     * Gets or sets the symbol identifier.
     * @type {string}
     * @memberof V1Symbol
     */
    symbol_id?: string | null;
    /**
     * Gets or sets the exchange identifier.
     * @type {string}
     * @memberof V1Symbol
     */
    exchange_id?: string | null;
    /**
     * Gets or sets the symbol type.
     * @type {string}
     * @memberof V1Symbol
     */
    symbol_type?: string | null;
    /**
     * Gets or sets the base asset identifier.
     * @type {string}
     * @memberof V1Symbol
     */
    asset_id_base?: string | null;
    /**
     * Gets or sets the quote asset identifier.
     * @type {string}
     * @memberof V1Symbol
     */
    asset_id_quote?: string | null;
    /**
     * Gets or sets the unit asset identifier.
     * @type {string}
     * @memberof V1Symbol
     */
    asset_id_unit?: string | null;
    /**
     * Gets or sets the contract unit for futures.
     * @type {number}
     * @memberof V1Symbol
     */
    future_contract_unit?: number | null;
    /**
     * Gets or sets the asset used as the unit for futures contract.
     * @type {string}
     * @memberof V1Symbol
     */
    future_contract_unit_asset?: string | null;
    /**
     * Gets or sets the future delivery time for futures contract.
     * @type {string}
     * @memberof V1Symbol
     */
    future_delivery_time?: string | null;
    /**
     * Gets or sets a value indicating whether the option type is a call.
     * @type {boolean}
     * @memberof V1Symbol
     */
    option_type_is_call?: boolean | null;
    /**
     * Gets or sets the strike price for options.
     * @type {number}
     * @memberof V1Symbol
     */
    option_strike_price?: number | null;
    /**
     * Gets or sets the contract unit for options.
     * @type {number}
     * @memberof V1Symbol
     */
    option_contract_unit?: number | null;
    /**
     * Gets or sets the exercise style for options. Possible values: AMERICAN, ASIAN, BARRIER, BERMUDAN, BINARY, EUROPEAN, EXOTIC.
     * @type {string}
     * @memberof V1Symbol
     */
    option_exercise_style?: string | null;
    /**
     * Gets or sets the expiration time for options.
     * @type {string}
     * @memberof V1Symbol
     */
    option_expiration_time?: string | null;
    /**
     * Gets or sets the delivery time for contracts.
     * @type {string}
     * @memberof V1Symbol
     */
    contract_delivery_time?: string | null;
    /**
     * Gets or sets the contract unit for contracts.
     * @type {number}
     * @memberof V1Symbol
     */
    contract_unit?: number | null;
    /**
     * Gets or sets the asset used as the unit for contracts.
     * @type {string}
     * @memberof V1Symbol
     */
    contract_unit_asset?: string | null;
    /**
     * Gets or sets the contract identifier.
     * @type {string}
     * @memberof V1Symbol
     */
    contract_id?: string | null;
    /**
     * Gets or sets the display name of the contract.
     * @type {string}
     * @memberof V1Symbol
     */
    contract_display_name?: string | null;
    /**
     * Gets or sets the display description of the contract.
     * @type {string}
     * @memberof V1Symbol
     */
    contract_display_description?: string | null;
    /**
     * Gets the start date of the data in string format (\"yyyy-MM-dd\").
     * @type {string}
     * @memberof V1Symbol
     */
    readonly data_start?: string | null;
    /**
     * Gets the end date of the data in string format (\"yyyy-MM-dd\").
     * @type {string}
     * @memberof V1Symbol
     */
    readonly data_end?: string | null;
    /**
     * Gets or sets the start date of quote data.
     * @type {string}
     * @memberof V1Symbol
     */
    data_quote_start?: string | null;
    /**
     * Gets or sets the end date of quote data.
     * @type {string}
     * @memberof V1Symbol
     */
    data_quote_end?: string | null;
    /**
     * Gets or sets the start date of order book data.
     * @type {string}
     * @memberof V1Symbol
     */
    data_orderbook_start?: string | null;
    /**
     * Gets or sets the end date of order book data.
     * @type {string}
     * @memberof V1Symbol
     */
    data_orderbook_end?: string | null;
    /**
     * Gets or sets the start date of trade data.
     * @type {string}
     * @memberof V1Symbol
     */
    data_trade_start?: string | null;
    /**
     * Gets or sets the end date of trade data.
     * @type {string}
     * @memberof V1Symbol
     */
    data_trade_end?: string | null;
    /**
     * Gets or sets the index identifier.
     * @type {string}
     * @memberof V1Symbol
     */
    index_id?: string | null;
    /**
     * Gets or sets the display name of the index.
     * @type {string}
     * @memberof V1Symbol
     */
    index_display_name?: string | null;
    /**
     * Gets or sets the display description of the index.
     * @type {string}
     * @memberof V1Symbol
     */
    index_display_description?: string | null;
    /**
     * Gets or sets the volume in the last 1 hour.
     * @type {number}
     * @memberof V1Symbol
     */
    volume_1hrs?: number | null;
    /**
     * Gets or sets the volume in USD in the last 1 hour.
     * @type {number}
     * @memberof V1Symbol
     */
    volume_1hrs_usd?: number | null;
    /**
     * Gets or sets the volume in the last 1 day.
     * @type {number}
     * @memberof V1Symbol
     */
    volume_1day?: number | null;
    /**
     * Gets or sets the volume in USD in the last 1 day.
     * @type {number}
     * @memberof V1Symbol
     */
    volume_1day_usd?: number | null;
    /**
     * Gets or sets the volume in the last 1 month.
     * @type {number}
     * @memberof V1Symbol
     */
    volume_1mth?: number | null;
    /**
     * Gets or sets the volume in USD in the last 1 month.
     * @type {number}
     * @memberof V1Symbol
     */
    volume_1mth_usd?: number | null;
    /**
     * Gets or sets the price.
     * @type {number}
     * @memberof V1Symbol
     */
    price?: number | null;
    /**
     * Gets or sets the symbol identifier in the exchange.
     * @type {string}
     * @memberof V1Symbol
     */
    symbol_id_exchange?: string | null;
    /**
     * Gets or sets the base asset identifier in the exchange.
     * @type {string}
     * @memberof V1Symbol
     */
    asset_id_base_exchange?: string | null;
    /**
     * Gets or sets the quote asset identifier in the exchange.
     * @type {string}
     * @memberof V1Symbol
     */
    asset_id_quote_exchange?: string | null;
    /**
     * Gets or sets the price precision.
     * @type {number}
     * @memberof V1Symbol
     */
    price_precision?: number | null;
    /**
     * Gets or sets the size precision.
     * @type {number}
     * @memberof V1Symbol
     */
    size_precision?: number | null;
    /**
     * Key Value Pair store with raw data from the data source.
     * @type {{ [key: string]: string | null; }}
     * @memberof V1Symbol
     */
    raw_kvp?: { [key: string]: string | null; } | null;
    /**
     * Gets or sets a value indicating whether the futures contract is inverse (coin-margined).
     * @type {boolean}
     * @memberof V1Symbol
     */
    future_is_inverse?: boolean | null;
    /**
     * Gets or sets a value indicating whether the futures contract is quanto.
     * @type {boolean}
     * @memberof V1Symbol
     */
    future_is_quanto?: boolean | null;
    /**
     * Gets or sets the volume in USD.
     * @type {number}
     * @memberof V1Symbol
     */
    volume_to_usd?: number | null;
    /**
     * Gets or sets the up barrier price for barrier options.
     * @type {number}
     * @memberof V1Symbol
     */
    option_barrier_up_price?: number | null;
    /**
     * Gets or sets the up barrier type for barrier options. Possible values: EXPIRATION, IN, OUT.
     * @type {string}
     * @memberof V1Symbol
     */
    option_barrier_up_type?: string | null;
    /**
     * Gets or sets the down barrier price for barrier options.
     * @type {number}
     * @memberof V1Symbol
     */
    option_barrier_down_price?: number | null;
    /**
     * Gets or sets the down barrier type for barrier options. Possible values: EXPIRATION, IN, OUT.
     * @type {string}
     * @memberof V1Symbol
     */
    option_barrier_down_type?: string | null;
    /**
     * Gets or sets the symbol identifier in integer immutable format, used to correlate data across different APIs.
     * @type {number}
     * @memberof V1Symbol
     */
    readonly symbol_id_int?: number | null;
}
