// tslint:disable
/**
 * CoinAPI Market Data REST API
 * Cryptocurrency market data: metadata, quotes, books, trades, OHLCV, rates, metrics, options.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents a timeseries period used in exchange rate data.
 * @export
 * @interface V1TimeseriesPeriod
 */
export interface V1TimeseriesPeriod {
    /**
     * Gets or sets the period ID.
     * @type {string}
     * @memberof V1TimeseriesPeriod
     */
    period_id?: string | null;
    /**
     * Gets or sets the length of the period in seconds.
     * @type {number}
     * @memberof V1TimeseriesPeriod
     */
    length_seconds?: number;
    /**
     * Gets or sets the length of the period in months.
     * @type {number}
     * @memberof V1TimeseriesPeriod
     */
    length_months?: number;
    /**
     * Gets or sets the unit count.
     * @type {number}
     * @memberof V1TimeseriesPeriod
     */
    unit_count?: number | null;
    /**
     * Gets or sets the unit name.
     * @type {string}
     * @memberof V1TimeseriesPeriod
     */
    unit_name?: string | null;
    /**
     * Gets or sets the display name of the timeseries period.
     * @type {string}
     * @memberof V1TimeseriesPeriod
     */
    display_name?: string | null;
}
