/**
 * CoinAPI Market Data REST API
 * Cryptocurrency market data: metadata, quotes, books, trades, OHLCV, rates, metrics, options.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Represents an exchange rate within a collection of exchange rates.
 */
export interface V1ExchangeRatesRate {
    /**
     * Gets or sets the time of the exchange rate.
     */
    time?: string;

    /**
     * Gets or sets the quote asset ID of the exchange rate.
     */
    asset_id_quote?: string;

    /**
     * Gets or sets the exchange rate value.
     */
    rate?: number;

}
