/**
 * CoinAPI Market Data REST API
 * Cryptocurrency market data: metadata, quotes, books, trades, OHLCV, rates, metrics, options.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Represents a symbol data model.
 */
export interface V1Symbol {
    /**
     * Gets or sets the symbol identifier.
     */
    symbol_id?: string;

    /**
     * Gets or sets the exchange identifier.
     */
    exchange_id?: string;

    /**
     * Gets or sets the symbol type.
     */
    symbol_type?: string;

    /**
     * Gets or sets the base asset identifier.
     */
    asset_id_base?: string;

    /**
     * Gets or sets the quote asset identifier.
     */
    asset_id_quote?: string;

    /**
     * Gets or sets the unit asset identifier.
     */
    asset_id_unit?: string;

    /**
     * Gets or sets the contract unit for futures.
     */
    future_contract_unit?: number;

    /**
     * Gets or sets the asset used as the unit for futures contract.
     */
    future_contract_unit_asset?: string;

    /**
     * Gets or sets the future delivery time for futures contract.
     */
    future_delivery_time?: string;

    /**
     * Gets or sets a value indicating whether the option type is a call.
     */
    option_type_is_call?: boolean;

    /**
     * Gets or sets the strike price for options.
     */
    option_strike_price?: number;

    /**
     * Gets or sets the contract unit for options.
     */
    option_contract_unit?: number;

    /**
     * Gets or sets the exercise style for options. Possible values: AMERICAN, ASIAN, BARRIER, BERMUDAN, BINARY, EUROPEAN, EXOTIC.
     */
    option_exercise_style?: string;

    /**
     * Gets or sets the expiration time for options.
     */
    option_expiration_time?: string;

    /**
     * Gets or sets the delivery time for contracts.
     */
    contract_delivery_time?: string;

    /**
     * Gets or sets the contract unit for contracts.
     */
    contract_unit?: number;

    /**
     * Gets or sets the asset used as the unit for contracts.
     */
    contract_unit_asset?: string;

    /**
     * Gets or sets the contract identifier.
     */
    contract_id?: string;

    /**
     * Gets or sets the display name of the contract.
     */
    contract_display_name?: string;

    /**
     * Gets or sets the display description of the contract.
     */
    contract_display_description?: string;

    /**
     * Gets the start date of the data in string format (\"yyyy-MM-dd\").
     */
    data_start?: string;

    /**
     * Gets the end date of the data in string format (\"yyyy-MM-dd\").
     */
    data_end?: string;

    /**
     * Gets or sets the start date of quote data.
     */
    data_quote_start?: string;

    /**
     * Gets or sets the end date of quote data.
     */
    data_quote_end?: string;

    /**
     * Gets or sets the start date of order book data.
     */
    data_orderbook_start?: string;

    /**
     * Gets or sets the end date of order book data.
     */
    data_orderbook_end?: string;

    /**
     * Gets or sets the start date of trade data.
     */
    data_trade_start?: string;

    /**
     * Gets or sets the end date of trade data.
     */
    data_trade_end?: string;

    /**
     * Gets or sets the index identifier.
     */
    index_id?: string;

    /**
     * Gets or sets the display name of the index.
     */
    index_display_name?: string;

    /**
     * Gets or sets the display description of the index.
     */
    index_display_description?: string;

    /**
     * Gets or sets the volume in the last 1 hour.
     */
    volume_1hrs?: number;

    /**
     * Gets or sets the volume in USD in the last 1 hour.
     */
    volume_1hrs_usd?: number;

    /**
     * Gets or sets the volume in the last 1 day.
     */
    volume_1day?: number;

    /**
     * Gets or sets the volume in USD in the last 1 day.
     */
    volume_1day_usd?: number;

    /**
     * Gets or sets the volume in the last 1 month.
     */
    volume_1mth?: number;

    /**
     * Gets or sets the volume in USD in the last 1 month.
     */
    volume_1mth_usd?: number;

    /**
     * Gets or sets the price.
     */
    price?: number;

    /**
     * Gets or sets the symbol identifier in the exchange.
     */
    symbol_id_exchange?: string;

    /**
     * Gets or sets the base asset identifier in the exchange.
     */
    asset_id_base_exchange?: string;

    /**
     * Gets or sets the quote asset identifier in the exchange.
     */
    asset_id_quote_exchange?: string;

    /**
     * Gets or sets the price precision.
     */
    price_precision?: number;

    /**
     * Gets or sets the size precision.
     */
    size_precision?: number;

    /**
     * Key Value Pair store with raw data from the data source.
     */
    raw_kvp?: { [key: string]: string | null; };

    /**
     * Gets or sets a value indicating whether the futures contract is inverse (coin-margined).
     */
    future_is_inverse?: boolean;

    /**
     * Gets or sets a value indicating whether the futures contract is quanto.
     */
    future_is_quanto?: boolean;

    /**
     * Gets or sets the volume in USD.
     */
    volume_to_usd?: number;

    /**
     * Gets or sets the up barrier price for barrier options.
     */
    option_barrier_up_price?: number;

    /**
     * Gets or sets the up barrier type for barrier options. Possible values: EXPIRATION, IN, OUT.
     */
    option_barrier_up_type?: string;

    /**
     * Gets or sets the down barrier price for barrier options.
     */
    option_barrier_down_price?: number;

    /**
     * Gets or sets the down barrier type for barrier options. Possible values: EXPIRATION, IN, OUT.
     */
    option_barrier_down_type?: string;

    /**
     * Gets or sets the symbol identifier in integer immutable format, used to correlate data across different APIs.
     */
    symbol_id_int?: number;

}
