--[[
  FinFeedAPI Stock REST API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: v1
  Contact: support@apibricks.io
  Generated by: https://openapi-generator.tech
]]

-- iex_price_level_update_price_level_update_model class
local iex_price_level_update_price_level_update_model = {}
local iex_price_level_update_price_level_update_model_mt = {
	__name = "iex_price_level_update_price_level_update_model";
	__index = iex_price_level_update_price_level_update_model;
}

local function cast_iex_price_level_update_price_level_update_model(t)
	return setmetatable(t, iex_price_level_update_price_level_update_model_mt)
end

local function new_iex_price_level_update_price_level_update_model(symbol, timestamp_nanos, timestamp, is_side_buy, is_event_processing_complete, size, price)
	return cast_iex_price_level_update_price_level_update_model({
		["symbol"] = symbol;
		["timestamp_nanos"] = timestamp_nanos;
		["timestamp"] = timestamp;
		["is_side_buy"] = is_side_buy;
		["is_event_processing_complete"] = is_event_processing_complete;
		["size"] = size;
		["price"] = price;
	})
end

return {
	cast = cast_iex_price_level_update_price_level_update_model;
	new = new_iex_price_level_update_price_level_update_model;
}
