--[[
  FinFeedAPI Stock REST API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: v1
  Contact: support@apibricks.io
  Generated by: https://openapi-generator.tech
]]

-- models_security_directory_model class
local models_security_directory_model = {}
local models_security_directory_model_mt = {
	__name = "models_security_directory_model";
	__index = models_security_directory_model;
}

local function cast_models_security_directory_model(t)
	return setmetatable(t, models_security_directory_model_mt)
end

local function new_models_security_directory_model(symbol, timestamp_nanos, timestamp, flags, round_lot_size, adjusted_poc_price, luld_tier, luld_tier_code, luld_tier_text, is_luld_tier_not_applicable, is_luld_tier1, is_luld_tier2)
	return cast_models_security_directory_model({
		["symbol"] = symbol;
		["timestamp_nanos"] = timestamp_nanos;
		["timestamp"] = timestamp;
		["flags"] = flags;
		["round_lot_size"] = round_lot_size;
		["adjusted_poc_price"] = adjusted_poc_price;
		["luld_tier"] = luld_tier;
		["luld_tier_code"] = luld_tier_code;
		["luld_tier_text"] = luld_tier_text;
		["is_luld_tier_not_applicable"] = is_luld_tier_not_applicable;
		["is_luld_tier1"] = is_luld_tier1;
		["is_luld_tier2"] = is_luld_tier2;
	})
end

return {
	cast = cast_models_security_directory_model;
	new = new_models_security_directory_model;
}
