# coding: utf-8

"""
    FX Realtime REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: support@apibricks.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api_bricks_currencies_api_rest_realtime.api.rate_limit_api import RateLimitApi


class TestRateLimitApi(unittest.TestCase):
    """RateLimitApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RateLimitApi()

    def tearDown(self) -> None:
        pass

    def test_internal_ratelimit_wsconcon_apikey_get(self) -> None:
        """Test case for internal_ratelimit_wsconcon_apikey_get

        """
        pass

    def test_internal_ratelimit_wshello_ip_get(self) -> None:
        """Test case for internal_ratelimit_wshello_ip_get

        """
        pass

    def test_internal_ratelimit_wsreq_ip_get(self) -> None:
        """Test case for internal_ratelimit_wsreq_ip_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
