--[[
  CoinAPI Indexes REST API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: v1
  Contact: support@apibricks.io
  Generated by: https://openapi-generator.tech
]]

-- models_index_definition_snapshot_entry class
local models_index_definition_snapshot_entry = {}
local models_index_definition_snapshot_entry_mt = {
	__name = "models_index_definition_snapshot_entry";
	__index = models_index_definition_snapshot_entry;
}

local function cast_models_index_definition_snapshot_entry(t)
	return setmetatable(t, models_index_definition_snapshot_entry_mt)
end

local function new_models_index_definition_snapshot_entry(index_id, timestamp, value)
	return cast_models_index_definition_snapshot_entry({
		["index_id"] = index_id;
		["timestamp"] = timestamp;
		["value"] = value;
	})
end

return {
	cast = cast_models_index_definition_snapshot_entry;
	new = new_models_index_definition_snapshot_entry;
}
