--[[
  CoinAPI Market Data REST API

  Cryptocurrency market data: metadata, quotes, books, trades, OHLCV, rates, metrics, options.

  The version of the OpenAPI document: v1
  Contact: support@apibricks.io
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for openapiclient.model.market_data_metadata_icon
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("market_data_metadata_icon", function()
  local openapiclient_market_data_metadata_icon = require "openapiclient.model.market_data_metadata_icon"

  -- unit tests for the property 'exchange_id'
  describe("property exchange_id test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'asset_id'
  describe("property asset_id test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'url'
  describe("property url test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
