--[[
  CoinAPI Market Data REST API

  Cryptocurrency market data: metadata, quotes, books, trades, OHLCV, rates, metrics, options.

  The version of the OpenAPI document: v1
  Contact: support@apibricks.io
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for openapiclient.model.market_data_metadata_chain
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("market_data_metadata_chain", function()
  local openapiclient_market_data_metadata_chain = require "openapiclient.model.market_data_metadata_chain"

  -- unit tests for the property 'chain_id'
  describe("property chain_id test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'name'
  describe("property name test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
