--[[
  CoinAPI Market Data REST API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: v1
  Contact: support@apibricks.io
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for openapiclient.api.metrics_v2_api
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("metrics_v2_api", function()
  local openapiclient_metrics_v2_api = require "openapiclient.api.metrics_v2_api"
  -- unit tests for marketdata_list_metrics_v2_asset_history
  describe("marketdata_list_metrics_v2_asset_history test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for marketdata_list_metrics_v2_asset_listing
  describe("marketdata_list_metrics_v2_asset_listing test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for marketdata_list_metrics_v2_chain_history
  describe("marketdata_list_metrics_v2_chain_history test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for marketdata_list_metrics_v2_chain_listing
  describe("marketdata_list_metrics_v2_chain_listing test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for marketdata_list_metrics_v2_exchange_history
  describe("marketdata_list_metrics_v2_exchange_history test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for marketdata_list_metrics_v2_exchange_listing
  describe("marketdata_list_metrics_v2_exchange_listing test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for marketdata_list_metrics_v2_listing
  describe("marketdata_list_metrics_v2_listing test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
