--[[
  CoinAPI Market Data REST API

  Cryptocurrency market data: metadata, quotes, books, trades, OHLCV, rates, metrics, options.

  The version of the OpenAPI document: v1
  Contact: support@apibricks.io
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for openapiclient.model.v1_metric_data
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("v1_metric_data", function()
  local openapiclient_v1_metric_data = require "openapiclient.model.v1_metric_data"

  -- unit tests for the property 'symbol_id'
  describe("property symbol_id test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'time'
  describe("property time test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'value'
  describe("property value test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
