/*
FinFeedAPI Stock REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: support@apibricks.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ModelsAdminMessageModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsAdminMessageModel{}

// ModelsAdminMessageModel Represents the response DTO for IEX admin information, combining all symbol-based admin message types
type ModelsAdminMessageModel struct {
	TradingStatus *ModelsTradingStatusModel `json:"trading_status,omitempty"`
	OfficialPrice *ModelsOfficialPriceModel `json:"official_price,omitempty"`
	SecurityEvent *ModelsSecurityEventModel `json:"security_event,omitempty"`
	AuctionInformation *ModelsAuctionInformationModel `json:"auction_information,omitempty"`
	ShortSalePriceTest *ModelsShortSalePriceTestStatusModel `json:"short_sale_price_test,omitempty"`
	OperationalHaltStatus *ModelsOperationalHaltStatusModel `json:"operational_halt_status,omitempty"`
	RetailLiquidityIndicator *ModelsRetailLiquidityIndicatorModel `json:"retail_liquidity_indicator,omitempty"`
	SystemEvent *IEXSystemEventSystemEventModel `json:"system_event,omitempty"`
	SecurityDirectory *ModelsSecurityDirectoryModel `json:"security_directory,omitempty"`
}

// NewModelsAdminMessageModel instantiates a new ModelsAdminMessageModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsAdminMessageModel() *ModelsAdminMessageModel {
	this := ModelsAdminMessageModel{}
	return &this
}

// NewModelsAdminMessageModelWithDefaults instantiates a new ModelsAdminMessageModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsAdminMessageModelWithDefaults() *ModelsAdminMessageModel {
	this := ModelsAdminMessageModel{}
	return &this
}

// GetTradingStatus returns the TradingStatus field value if set, zero value otherwise.
func (o *ModelsAdminMessageModel) GetTradingStatus() ModelsTradingStatusModel {
	if o == nil || IsNil(o.TradingStatus) {
		var ret ModelsTradingStatusModel
		return ret
	}
	return *o.TradingStatus
}

// GetTradingStatusOk returns a tuple with the TradingStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsAdminMessageModel) GetTradingStatusOk() (*ModelsTradingStatusModel, bool) {
	if o == nil || IsNil(o.TradingStatus) {
		return nil, false
	}
	return o.TradingStatus, true
}

// HasTradingStatus returns a boolean if a field has been set.
func (o *ModelsAdminMessageModel) HasTradingStatus() bool {
	if o != nil && !IsNil(o.TradingStatus) {
		return true
	}

	return false
}

// SetTradingStatus gets a reference to the given ModelsTradingStatusModel and assigns it to the TradingStatus field.
func (o *ModelsAdminMessageModel) SetTradingStatus(v ModelsTradingStatusModel) {
	o.TradingStatus = &v
}

// GetOfficialPrice returns the OfficialPrice field value if set, zero value otherwise.
func (o *ModelsAdminMessageModel) GetOfficialPrice() ModelsOfficialPriceModel {
	if o == nil || IsNil(o.OfficialPrice) {
		var ret ModelsOfficialPriceModel
		return ret
	}
	return *o.OfficialPrice
}

// GetOfficialPriceOk returns a tuple with the OfficialPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsAdminMessageModel) GetOfficialPriceOk() (*ModelsOfficialPriceModel, bool) {
	if o == nil || IsNil(o.OfficialPrice) {
		return nil, false
	}
	return o.OfficialPrice, true
}

// HasOfficialPrice returns a boolean if a field has been set.
func (o *ModelsAdminMessageModel) HasOfficialPrice() bool {
	if o != nil && !IsNil(o.OfficialPrice) {
		return true
	}

	return false
}

// SetOfficialPrice gets a reference to the given ModelsOfficialPriceModel and assigns it to the OfficialPrice field.
func (o *ModelsAdminMessageModel) SetOfficialPrice(v ModelsOfficialPriceModel) {
	o.OfficialPrice = &v
}

// GetSecurityEvent returns the SecurityEvent field value if set, zero value otherwise.
func (o *ModelsAdminMessageModel) GetSecurityEvent() ModelsSecurityEventModel {
	if o == nil || IsNil(o.SecurityEvent) {
		var ret ModelsSecurityEventModel
		return ret
	}
	return *o.SecurityEvent
}

// GetSecurityEventOk returns a tuple with the SecurityEvent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsAdminMessageModel) GetSecurityEventOk() (*ModelsSecurityEventModel, bool) {
	if o == nil || IsNil(o.SecurityEvent) {
		return nil, false
	}
	return o.SecurityEvent, true
}

// HasSecurityEvent returns a boolean if a field has been set.
func (o *ModelsAdminMessageModel) HasSecurityEvent() bool {
	if o != nil && !IsNil(o.SecurityEvent) {
		return true
	}

	return false
}

// SetSecurityEvent gets a reference to the given ModelsSecurityEventModel and assigns it to the SecurityEvent field.
func (o *ModelsAdminMessageModel) SetSecurityEvent(v ModelsSecurityEventModel) {
	o.SecurityEvent = &v
}

// GetAuctionInformation returns the AuctionInformation field value if set, zero value otherwise.
func (o *ModelsAdminMessageModel) GetAuctionInformation() ModelsAuctionInformationModel {
	if o == nil || IsNil(o.AuctionInformation) {
		var ret ModelsAuctionInformationModel
		return ret
	}
	return *o.AuctionInformation
}

// GetAuctionInformationOk returns a tuple with the AuctionInformation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsAdminMessageModel) GetAuctionInformationOk() (*ModelsAuctionInformationModel, bool) {
	if o == nil || IsNil(o.AuctionInformation) {
		return nil, false
	}
	return o.AuctionInformation, true
}

// HasAuctionInformation returns a boolean if a field has been set.
func (o *ModelsAdminMessageModel) HasAuctionInformation() bool {
	if o != nil && !IsNil(o.AuctionInformation) {
		return true
	}

	return false
}

// SetAuctionInformation gets a reference to the given ModelsAuctionInformationModel and assigns it to the AuctionInformation field.
func (o *ModelsAdminMessageModel) SetAuctionInformation(v ModelsAuctionInformationModel) {
	o.AuctionInformation = &v
}

// GetShortSalePriceTest returns the ShortSalePriceTest field value if set, zero value otherwise.
func (o *ModelsAdminMessageModel) GetShortSalePriceTest() ModelsShortSalePriceTestStatusModel {
	if o == nil || IsNil(o.ShortSalePriceTest) {
		var ret ModelsShortSalePriceTestStatusModel
		return ret
	}
	return *o.ShortSalePriceTest
}

// GetShortSalePriceTestOk returns a tuple with the ShortSalePriceTest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsAdminMessageModel) GetShortSalePriceTestOk() (*ModelsShortSalePriceTestStatusModel, bool) {
	if o == nil || IsNil(o.ShortSalePriceTest) {
		return nil, false
	}
	return o.ShortSalePriceTest, true
}

// HasShortSalePriceTest returns a boolean if a field has been set.
func (o *ModelsAdminMessageModel) HasShortSalePriceTest() bool {
	if o != nil && !IsNil(o.ShortSalePriceTest) {
		return true
	}

	return false
}

// SetShortSalePriceTest gets a reference to the given ModelsShortSalePriceTestStatusModel and assigns it to the ShortSalePriceTest field.
func (o *ModelsAdminMessageModel) SetShortSalePriceTest(v ModelsShortSalePriceTestStatusModel) {
	o.ShortSalePriceTest = &v
}

// GetOperationalHaltStatus returns the OperationalHaltStatus field value if set, zero value otherwise.
func (o *ModelsAdminMessageModel) GetOperationalHaltStatus() ModelsOperationalHaltStatusModel {
	if o == nil || IsNil(o.OperationalHaltStatus) {
		var ret ModelsOperationalHaltStatusModel
		return ret
	}
	return *o.OperationalHaltStatus
}

// GetOperationalHaltStatusOk returns a tuple with the OperationalHaltStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsAdminMessageModel) GetOperationalHaltStatusOk() (*ModelsOperationalHaltStatusModel, bool) {
	if o == nil || IsNil(o.OperationalHaltStatus) {
		return nil, false
	}
	return o.OperationalHaltStatus, true
}

// HasOperationalHaltStatus returns a boolean if a field has been set.
func (o *ModelsAdminMessageModel) HasOperationalHaltStatus() bool {
	if o != nil && !IsNil(o.OperationalHaltStatus) {
		return true
	}

	return false
}

// SetOperationalHaltStatus gets a reference to the given ModelsOperationalHaltStatusModel and assigns it to the OperationalHaltStatus field.
func (o *ModelsAdminMessageModel) SetOperationalHaltStatus(v ModelsOperationalHaltStatusModel) {
	o.OperationalHaltStatus = &v
}

// GetRetailLiquidityIndicator returns the RetailLiquidityIndicator field value if set, zero value otherwise.
func (o *ModelsAdminMessageModel) GetRetailLiquidityIndicator() ModelsRetailLiquidityIndicatorModel {
	if o == nil || IsNil(o.RetailLiquidityIndicator) {
		var ret ModelsRetailLiquidityIndicatorModel
		return ret
	}
	return *o.RetailLiquidityIndicator
}

// GetRetailLiquidityIndicatorOk returns a tuple with the RetailLiquidityIndicator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsAdminMessageModel) GetRetailLiquidityIndicatorOk() (*ModelsRetailLiquidityIndicatorModel, bool) {
	if o == nil || IsNil(o.RetailLiquidityIndicator) {
		return nil, false
	}
	return o.RetailLiquidityIndicator, true
}

// HasRetailLiquidityIndicator returns a boolean if a field has been set.
func (o *ModelsAdminMessageModel) HasRetailLiquidityIndicator() bool {
	if o != nil && !IsNil(o.RetailLiquidityIndicator) {
		return true
	}

	return false
}

// SetRetailLiquidityIndicator gets a reference to the given ModelsRetailLiquidityIndicatorModel and assigns it to the RetailLiquidityIndicator field.
func (o *ModelsAdminMessageModel) SetRetailLiquidityIndicator(v ModelsRetailLiquidityIndicatorModel) {
	o.RetailLiquidityIndicator = &v
}

// GetSystemEvent returns the SystemEvent field value if set, zero value otherwise.
func (o *ModelsAdminMessageModel) GetSystemEvent() IEXSystemEventSystemEventModel {
	if o == nil || IsNil(o.SystemEvent) {
		var ret IEXSystemEventSystemEventModel
		return ret
	}
	return *o.SystemEvent
}

// GetSystemEventOk returns a tuple with the SystemEvent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsAdminMessageModel) GetSystemEventOk() (*IEXSystemEventSystemEventModel, bool) {
	if o == nil || IsNil(o.SystemEvent) {
		return nil, false
	}
	return o.SystemEvent, true
}

// HasSystemEvent returns a boolean if a field has been set.
func (o *ModelsAdminMessageModel) HasSystemEvent() bool {
	if o != nil && !IsNil(o.SystemEvent) {
		return true
	}

	return false
}

// SetSystemEvent gets a reference to the given IEXSystemEventSystemEventModel and assigns it to the SystemEvent field.
func (o *ModelsAdminMessageModel) SetSystemEvent(v IEXSystemEventSystemEventModel) {
	o.SystemEvent = &v
}

// GetSecurityDirectory returns the SecurityDirectory field value if set, zero value otherwise.
func (o *ModelsAdminMessageModel) GetSecurityDirectory() ModelsSecurityDirectoryModel {
	if o == nil || IsNil(o.SecurityDirectory) {
		var ret ModelsSecurityDirectoryModel
		return ret
	}
	return *o.SecurityDirectory
}

// GetSecurityDirectoryOk returns a tuple with the SecurityDirectory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsAdminMessageModel) GetSecurityDirectoryOk() (*ModelsSecurityDirectoryModel, bool) {
	if o == nil || IsNil(o.SecurityDirectory) {
		return nil, false
	}
	return o.SecurityDirectory, true
}

// HasSecurityDirectory returns a boolean if a field has been set.
func (o *ModelsAdminMessageModel) HasSecurityDirectory() bool {
	if o != nil && !IsNil(o.SecurityDirectory) {
		return true
	}

	return false
}

// SetSecurityDirectory gets a reference to the given ModelsSecurityDirectoryModel and assigns it to the SecurityDirectory field.
func (o *ModelsAdminMessageModel) SetSecurityDirectory(v ModelsSecurityDirectoryModel) {
	o.SecurityDirectory = &v
}

func (o ModelsAdminMessageModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsAdminMessageModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TradingStatus) {
		toSerialize["trading_status"] = o.TradingStatus
	}
	if !IsNil(o.OfficialPrice) {
		toSerialize["official_price"] = o.OfficialPrice
	}
	if !IsNil(o.SecurityEvent) {
		toSerialize["security_event"] = o.SecurityEvent
	}
	if !IsNil(o.AuctionInformation) {
		toSerialize["auction_information"] = o.AuctionInformation
	}
	if !IsNil(o.ShortSalePriceTest) {
		toSerialize["short_sale_price_test"] = o.ShortSalePriceTest
	}
	if !IsNil(o.OperationalHaltStatus) {
		toSerialize["operational_halt_status"] = o.OperationalHaltStatus
	}
	if !IsNil(o.RetailLiquidityIndicator) {
		toSerialize["retail_liquidity_indicator"] = o.RetailLiquidityIndicator
	}
	if !IsNil(o.SystemEvent) {
		toSerialize["system_event"] = o.SystemEvent
	}
	if !IsNil(o.SecurityDirectory) {
		toSerialize["security_directory"] = o.SecurityDirectory
	}
	return toSerialize, nil
}

type NullableModelsAdminMessageModel struct {
	value *ModelsAdminMessageModel
	isSet bool
}

func (v NullableModelsAdminMessageModel) Get() *ModelsAdminMessageModel {
	return v.value
}

func (v *NullableModelsAdminMessageModel) Set(val *ModelsAdminMessageModel) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsAdminMessageModel) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsAdminMessageModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsAdminMessageModel(val *ModelsAdminMessageModel) *NullableModelsAdminMessageModel {
	return &NullableModelsAdminMessageModel{value: val, isSet: true}
}

func (v NullableModelsAdminMessageModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsAdminMessageModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


