#
# CoinAPI Market Data REST API
# Cryptocurrency market data: metadata, quotes, books, trades, OHLCV, rates, metrics, options.
# Version: v1
# Contact: support@apibricks.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'V1Chain' {
    Context 'V1Chain' {
        It 'Initialize-V1Chain' {
            # a simple test to create an object
            #$NewObject = Initialize-V1Chain -ChainId "TEST_VALUE" -Name "TEST_VALUE"
            #$NewObject | Should -BeOfType V1Chain
            #$NewObject.property | Should -Be 0
        }
    }
}
