#
# CoinAPI Market Data REST API
# Cryptocurrency market data: metadata, quotes, books, trades, OHLCV, rates, metrics, options.
# Version: v1
# Contact: support@apibricks.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'V1ListingItem' {
    Context 'V1ListingItem' {
        It 'Initialize-V1ListingItem' {
            # a simple test to create an object
            #$NewObject = Initialize-V1ListingItem -MetricId "TEST_VALUE" -SymbolId "TEST_VALUE" -SymbolIdExternal "TEST_VALUE" -ExchangeId "TEST_VALUE" -AssetId "TEST_VALUE" -AssetIdExternal "TEST_VALUE" -ChainId "TEST_VALUE" -NetworkId "TEST_VALUE"
            #$NewObject | Should -BeOfType V1ListingItem
            #$NewObject.property | Should -Be 0
        }
    }
}
