/*
 * FinFeedAPI Stock REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.FinFeedAPIExchangeModel;
import org.openapitools.client.model.FinFeedAPISymbolModel;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MetadataApi
 */
@Disabled
public class MetadataApiTest {

    private final MetadataApi api = new MetadataApi();

    /**
     * List of exchanges
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1ExchangesGetTest() throws ApiException {
        List<FinFeedAPIExchangeModel> response = api.v1ExchangesGet();
        // TODO: test validations
    }

    /**
     * List of symbols for the exchange
     *
     * Results are paginated. Use &#x60;limit&#x60; and &#x60;page&#x60; to control page size and offset (default limit: 100, max: 10000, default page: 1).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1SymbolsExchangeIdGetTest() throws ApiException {
        String exchangeId = null;
        String filterSymbolId = null;
        Integer limit = null;
        Integer page = null;
        List<FinFeedAPISymbolModel> response = api.v1SymbolsExchangeIdGet(exchangeId, filterSymbolId, limit, page);
        // TODO: test validations
    }

}
