# coding: utf-8

"""
    CoinAPI Indexes REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: support@apibricks.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api_bricks_coinapi_indexes_api_rest.api.multi_asset_weights_api import MultiAssetWeightsApi


class TestMultiAssetWeightsApi(unittest.TestCase):
    """MultiAssetWeightsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MultiAssetWeightsApi()

    def tearDown(self) -> None:
        pass

    def test_v1_indexdef_multiasset_get(self) -> None:
        """Test case for v1_indexdef_multiasset_get

        Get all multi-asset weights
        """
        pass

    def test_v1_indexdef_multiasset_index_id_get(self) -> None:
        """Test case for v1_indexdef_multiasset_index_id_get

        Get multi-asset weights for specific index
        """
        pass


if __name__ == '__main__':
    unittest.main()
