# coding: utf-8

"""
    FinFeedAPI Currencies Historical REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: support@apibricks.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api_bricks_currencies_api_rest_historical.models.v1_exchange_rates_chain_network_address import V1ExchangeRatesChainNetworkAddress

class TestV1ExchangeRatesChainNetworkAddress(unittest.TestCase):
    """V1ExchangeRatesChainNetworkAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ExchangeRatesChainNetworkAddress:
        """Test V1ExchangeRatesChainNetworkAddress
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ExchangeRatesChainNetworkAddress`
        """
        model = V1ExchangeRatesChainNetworkAddress()
        if include_optional:
            return V1ExchangeRatesChainNetworkAddress(
                chain_id = '',
                network_id = '',
                address = ''
            )
        else:
            return V1ExchangeRatesChainNetworkAddress(
        )
        """

    def testV1ExchangeRatesChainNetworkAddress(self):
        """Test V1ExchangeRatesChainNetworkAddress"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
