/*
 * CoinAPI Indexes REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ModelsIndexDefinitionInputData;
import org.openapitools.client.model.ModelsIndexDefinitionSnapshotEntry;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for IndexInputDataApi
 */
@Disabled
public class IndexInputDataApiTest {

    private final IndexInputDataApi api = new IndexInputDataApi();

    /**
     * Returns all data inputs for a specific index definition
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1IndexdefInputDataIndexDefinitionIdAllGetTest() throws ApiException {
        String indexDefinitionId = null;
        List<ModelsIndexDefinitionInputData> response = api.v1IndexdefInputDataIndexDefinitionIdAllGet(indexDefinitionId);
        // TODO: test validations
    }

    /**
     * Returns data inputs for certain index definition and time
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1IndexdefInputDataIndexDefinitionIdGetTest() throws ApiException {
        String indexDefinitionId = null;
        OffsetDateTime time = null;
        Boolean enabledOnly = null;
        Boolean pendingOnly = null;
        String filterAssetId = null;
        Boolean withStatusInfo = null;
        List<ModelsIndexDefinitionSnapshotEntry> response = api.v1IndexdefInputDataIndexDefinitionIdGet(indexDefinitionId, time, enabledOnly, pendingOnly, filterAssetId, withStatusInfo);
        // TODO: test validations
    }

}
