/*
 * FinFeedAPI Stock REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Represents the response DTO for security event information
 **/
@ApiModel(description = "Represents the response DTO for security event information")
public class ModelsSecurityEventModel {
  
  @SerializedName("symbol")
  private String symbol = null;
  @SerializedName("timestamp_nanos")
  private Long timestampNanos = null;
  @SerializedName("timestamp")
  private Date timestamp = null;
  @SerializedName("security_event")
  private Integer securityEvent = null;
  @SerializedName("security_event_code")
  private String securityEventCode = null;
  @SerializedName("security_event_text")
  private String securityEventText = null;
  @SerializedName("is_opening_process_complete")
  private Boolean isOpeningProcessComplete = null;
  @SerializedName("is_closing_process_complete")
  private Boolean isClosingProcessComplete = null;

  /**
   * The stock symbol
   **/
  @ApiModelProperty(value = "The stock symbol")
  public String getSymbol() {
    return symbol;
  }
  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  /**
   * Original timestamp in nanoseconds since epoch
   **/
  @ApiModelProperty(value = "Original timestamp in nanoseconds since epoch")
  public Long getTimestampNanos() {
    return timestampNanos;
  }
  public void setTimestampNanos(Long timestampNanos) {
    this.timestampNanos = timestampNanos;
  }

  /**
   * Time when the security event was recorded as DateTime
   **/
  @ApiModelProperty(value = "Time when the security event was recorded as DateTime")
  public Date getTimestamp() {
    return timestamp;
  }
  public void setTimestamp(Date timestamp) {
    this.timestamp = timestamp;
  }

  /**
   * Security event as byte value
   **/
  @ApiModelProperty(value = "Security event as byte value")
  public Integer getSecurityEvent() {
    return securityEvent;
  }
  public void setSecurityEvent(Integer securityEvent) {
    this.securityEvent = securityEvent;
  }

  /**
   * Security event as character string ('O' or 'C')
   **/
  @ApiModelProperty(value = "Security event as character string ('O' or 'C')")
  public String getSecurityEventCode() {
    return securityEventCode;
  }
  public void setSecurityEventCode(String securityEventCode) {
    this.securityEventCode = securityEventCode;
  }

  /**
   * Human-readable description of the security event
   **/
  @ApiModelProperty(value = "Human-readable description of the security event")
  public String getSecurityEventText() {
    return securityEventText;
  }
  public void setSecurityEventText(String securityEventText) {
    this.securityEventText = securityEventText;
  }

  /**
   * Indicates if the security event is 'Opening Process Complete' ('O'/0x4f).
   **/
  @ApiModelProperty(value = "Indicates if the security event is 'Opening Process Complete' ('O'/0x4f).")
  public Boolean getIsOpeningProcessComplete() {
    return isOpeningProcessComplete;
  }
  public void setIsOpeningProcessComplete(Boolean isOpeningProcessComplete) {
    this.isOpeningProcessComplete = isOpeningProcessComplete;
  }

  /**
   * Indicates if the security event is 'Closing Process Complete' ('C'/0x43).
   **/
  @ApiModelProperty(value = "Indicates if the security event is 'Closing Process Complete' ('C'/0x43).")
  public Boolean getIsClosingProcessComplete() {
    return isClosingProcessComplete;
  }
  public void setIsClosingProcessComplete(Boolean isClosingProcessComplete) {
    this.isClosingProcessComplete = isClosingProcessComplete;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelsSecurityEventModel modelsSecurityEventModel = (ModelsSecurityEventModel) o;
    return (this.symbol == null ? modelsSecurityEventModel.symbol == null : this.symbol.equals(modelsSecurityEventModel.symbol)) &&
        (this.timestampNanos == null ? modelsSecurityEventModel.timestampNanos == null : this.timestampNanos.equals(modelsSecurityEventModel.timestampNanos)) &&
        (this.timestamp == null ? modelsSecurityEventModel.timestamp == null : this.timestamp.equals(modelsSecurityEventModel.timestamp)) &&
        (this.securityEvent == null ? modelsSecurityEventModel.securityEvent == null : this.securityEvent.equals(modelsSecurityEventModel.securityEvent)) &&
        (this.securityEventCode == null ? modelsSecurityEventModel.securityEventCode == null : this.securityEventCode.equals(modelsSecurityEventModel.securityEventCode)) &&
        (this.securityEventText == null ? modelsSecurityEventModel.securityEventText == null : this.securityEventText.equals(modelsSecurityEventModel.securityEventText)) &&
        (this.isOpeningProcessComplete == null ? modelsSecurityEventModel.isOpeningProcessComplete == null : this.isOpeningProcessComplete.equals(modelsSecurityEventModel.isOpeningProcessComplete)) &&
        (this.isClosingProcessComplete == null ? modelsSecurityEventModel.isClosingProcessComplete == null : this.isClosingProcessComplete.equals(modelsSecurityEventModel.isClosingProcessComplete));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.symbol == null ? 0: this.symbol.hashCode());
    result = 31 * result + (this.timestampNanos == null ? 0: this.timestampNanos.hashCode());
    result = 31 * result + (this.timestamp == null ? 0: this.timestamp.hashCode());
    result = 31 * result + (this.securityEvent == null ? 0: this.securityEvent.hashCode());
    result = 31 * result + (this.securityEventCode == null ? 0: this.securityEventCode.hashCode());
    result = 31 * result + (this.securityEventText == null ? 0: this.securityEventText.hashCode());
    result = 31 * result + (this.isOpeningProcessComplete == null ? 0: this.isOpeningProcessComplete.hashCode());
    result = 31 * result + (this.isClosingProcessComplete == null ? 0: this.isClosingProcessComplete.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelsSecurityEventModel {\n");
    
    sb.append("  symbol: ").append(symbol).append("\n");
    sb.append("  timestampNanos: ").append(timestampNanos).append("\n");
    sb.append("  timestamp: ").append(timestamp).append("\n");
    sb.append("  securityEvent: ").append(securityEvent).append("\n");
    sb.append("  securityEventCode: ").append(securityEventCode).append("\n");
    sb.append("  securityEventText: ").append(securityEventText).append("\n");
    sb.append("  isOpeningProcessComplete: ").append(isOpeningProcessComplete).append("\n");
    sb.append("  isClosingProcessComplete: ").append(isClosingProcessComplete).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
