/*
 * FinFeedAPI Stock REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import org.openapitools.client.model.ModelsAddOrderModel;
import org.openapitools.client.model.ModelsClearBookModel;
import org.openapitools.client.model.ModelsDeleteOrderModel;
import org.openapitools.client.model.ModelsExecutedOrderModel;
import org.openapitools.client.model.ModelsModifyOrderModel;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Represents the response DTO for Level-3 order book information
 **/
@ApiModel(description = "Represents the response DTO for Level-3 order book information")
public class ModelsOrderBookModel {
  
  @SerializedName("add_order")
  private ModelsAddOrderModel addOrder = null;
  @SerializedName("delete_order")
  private ModelsDeleteOrderModel deleteOrder = null;
  @SerializedName("modify_order")
  private ModelsModifyOrderModel modifyOrder = null;
  @SerializedName("executed_order")
  private ModelsExecutedOrderModel executedOrder = null;
  @SerializedName("clear_book")
  private ModelsClearBookModel clearBook = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public ModelsAddOrderModel getAddOrder() {
    return addOrder;
  }
  public void setAddOrder(ModelsAddOrderModel addOrder) {
    this.addOrder = addOrder;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ModelsDeleteOrderModel getDeleteOrder() {
    return deleteOrder;
  }
  public void setDeleteOrder(ModelsDeleteOrderModel deleteOrder) {
    this.deleteOrder = deleteOrder;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ModelsModifyOrderModel getModifyOrder() {
    return modifyOrder;
  }
  public void setModifyOrder(ModelsModifyOrderModel modifyOrder) {
    this.modifyOrder = modifyOrder;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ModelsExecutedOrderModel getExecutedOrder() {
    return executedOrder;
  }
  public void setExecutedOrder(ModelsExecutedOrderModel executedOrder) {
    this.executedOrder = executedOrder;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ModelsClearBookModel getClearBook() {
    return clearBook;
  }
  public void setClearBook(ModelsClearBookModel clearBook) {
    this.clearBook = clearBook;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelsOrderBookModel modelsOrderBookModel = (ModelsOrderBookModel) o;
    return (this.addOrder == null ? modelsOrderBookModel.addOrder == null : this.addOrder.equals(modelsOrderBookModel.addOrder)) &&
        (this.deleteOrder == null ? modelsOrderBookModel.deleteOrder == null : this.deleteOrder.equals(modelsOrderBookModel.deleteOrder)) &&
        (this.modifyOrder == null ? modelsOrderBookModel.modifyOrder == null : this.modifyOrder.equals(modelsOrderBookModel.modifyOrder)) &&
        (this.executedOrder == null ? modelsOrderBookModel.executedOrder == null : this.executedOrder.equals(modelsOrderBookModel.executedOrder)) &&
        (this.clearBook == null ? modelsOrderBookModel.clearBook == null : this.clearBook.equals(modelsOrderBookModel.clearBook));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.addOrder == null ? 0: this.addOrder.hashCode());
    result = 31 * result + (this.deleteOrder == null ? 0: this.deleteOrder.hashCode());
    result = 31 * result + (this.modifyOrder == null ? 0: this.modifyOrder.hashCode());
    result = 31 * result + (this.executedOrder == null ? 0: this.executedOrder.hashCode());
    result = 31 * result + (this.clearBook == null ? 0: this.clearBook.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelsOrderBookModel {\n");
    
    sb.append("  addOrder: ").append(addOrder).append("\n");
    sb.append("  deleteOrder: ").append(deleteOrder).append("\n");
    sb.append("  modifyOrder: ").append(modifyOrder).append("\n");
    sb.append("  executedOrder: ").append(executedOrder).append("\n");
    sb.append("  clearBook: ").append(clearBook).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
