/*
 * FinFeedAPI Stock REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Represents the response DTO for order delete information
 **/
@ApiModel(description = "Represents the response DTO for order delete information")
public class ModelsDeleteOrderModel {
  
  @SerializedName("symbol")
  private String symbol = null;
  @SerializedName("timestamp_nanos")
  private Long timestampNanos = null;
  @SerializedName("timestamp")
  private Date timestamp = null;
  @SerializedName("order_id_reference")
  private Long orderIdReference = null;

  /**
   * The stock symbol
   **/
  @ApiModelProperty(value = "The stock symbol")
  public String getSymbol() {
    return symbol;
  }
  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  /**
   * Original timestamp in nanoseconds since epoch
   **/
  @ApiModelProperty(value = "Original timestamp in nanoseconds since epoch")
  public Long getTimestampNanos() {
    return timestampNanos;
  }
  public void setTimestampNanos(Long timestampNanos) {
    this.timestampNanos = timestampNanos;
  }

  /**
   * Time when the order was deleted as DateTime
   **/
  @ApiModelProperty(value = "Time when the order was deleted as DateTime")
  public Date getTimestamp() {
    return timestamp;
  }
  public void setTimestamp(Date timestamp) {
    this.timestamp = timestamp;
  }

  /**
   * Order identifier reference
   **/
  @ApiModelProperty(value = "Order identifier reference")
  public Long getOrderIdReference() {
    return orderIdReference;
  }
  public void setOrderIdReference(Long orderIdReference) {
    this.orderIdReference = orderIdReference;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelsDeleteOrderModel modelsDeleteOrderModel = (ModelsDeleteOrderModel) o;
    return (this.symbol == null ? modelsDeleteOrderModel.symbol == null : this.symbol.equals(modelsDeleteOrderModel.symbol)) &&
        (this.timestampNanos == null ? modelsDeleteOrderModel.timestampNanos == null : this.timestampNanos.equals(modelsDeleteOrderModel.timestampNanos)) &&
        (this.timestamp == null ? modelsDeleteOrderModel.timestamp == null : this.timestamp.equals(modelsDeleteOrderModel.timestamp)) &&
        (this.orderIdReference == null ? modelsDeleteOrderModel.orderIdReference == null : this.orderIdReference.equals(modelsDeleteOrderModel.orderIdReference));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.symbol == null ? 0: this.symbol.hashCode());
    result = 31 * result + (this.timestampNanos == null ? 0: this.timestampNanos.hashCode());
    result = 31 * result + (this.timestamp == null ? 0: this.timestamp.hashCode());
    result = 31 * result + (this.orderIdReference == null ? 0: this.orderIdReference.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelsDeleteOrderModel {\n");
    
    sb.append("  symbol: ").append(symbol).append("\n");
    sb.append("  timestampNanos: ").append(timestampNanos).append("\n");
    sb.append("  timestamp: ").append(timestamp).append("\n");
    sb.append("  orderIdReference: ").append(orderIdReference).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
