// tslint:disable
/**
 * CoinAPI Indexes REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents an index id
 * @export
 * @interface ModelsIndexIdentifier
 */
export interface ModelsIndexIdentifier {
    /**
     * Index ID
     * @type {string}
     * @memberof ModelsIndexIdentifier
     */
    id?: string | null;
}
