# coding: utf-8

"""
    FinFeedAPI Stock REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: support@apibricks.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api_bricks_stock_api_rest.models.models_security_event_model import ModelsSecurityEventModel

class TestModelsSecurityEventModel(unittest.TestCase):
    """ModelsSecurityEventModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelsSecurityEventModel:
        """Test ModelsSecurityEventModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelsSecurityEventModel`
        """
        model = ModelsSecurityEventModel()
        if include_optional:
            return ModelsSecurityEventModel(
                symbol = '',
                timestamp_nanos = 56,
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                security_event = 56,
                security_event_code = '',
                security_event_text = '',
                is_opening_process_complete = True,
                is_closing_process_complete = True
            )
        else:
            return ModelsSecurityEventModel(
        )
        """

    def testModelsSecurityEventModel(self):
        """Test ModelsSecurityEventModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
