export * from './download.service';
import { DownloadService } from './download.service';
export * from './extractor.service';
import { ExtractorService } from './extractor.service';
export * from './filings.service';
import { FilingsService } from './filings.service';
export * from './fullText.service';
import { FullTextService } from './fullText.service';
export * from './xbrlConverter.service';
import { XbrlConverterService } from './xbrlConverter.service';
export const APIS = [DownloadService, ExtractorService, FilingsService, FullTextService, XbrlConverterService];
