// tslint:disable
/**
 * FinFeedAPI Stock REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents the response DTO for order modify information
 * @export
 * @interface ModelsModifyOrderModel
 */
export interface ModelsModifyOrderModel {
    /**
     * The stock symbol
     * @type {string}
     * @memberof ModelsModifyOrderModel
     */
    symbol?: string | null;
    /**
     * Original timestamp in nanoseconds since epoch
     * @type {number}
     * @memberof ModelsModifyOrderModel
     */
    timestamp_nanos?: number;
    /**
     * Time when the order was modified as DateTime (UTC)
     * @type {string}
     * @memberof ModelsModifyOrderModel
     */
    timestamp?: string;
    /**
     * Order identifier reference
     * @type {number}
     * @memberof ModelsModifyOrderModel
     */
    order_id_reference?: number;
    /**
     * Indicates if priority is reseted
     * @type {boolean}
     * @memberof ModelsModifyOrderModel
     */
    is_priority_reset?: boolean;
    /**
     * New total quoted size in number of shares
     * @type {number}
     * @memberof ModelsModifyOrderModel
     */
    size?: number;
    /**
     * Price as decimal
     * @type {number}
     * @memberof ModelsModifyOrderModel
     */
    price?: number;
}
