// tslint:disable
/**
 * FinFeedAPI Stock REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents the response DTO for clear book information
 * @export
 * @interface ModelsClearBookModel
 */
export interface ModelsClearBookModel {
    /**
     * The stock symbol
     * @type {string}
     * @memberof ModelsClearBookModel
     */
    symbol?: string | null;
    /**
     * Original timestamp in nanoseconds since epoch
     * @type {number}
     * @memberof ModelsClearBookModel
     */
    timestamp_nanos?: number;
    /**
     * Time when the book was cleared as DateTime
     * @type {string}
     * @memberof ModelsClearBookModel
     */
    timestamp?: string;
}
