# coding: utf-8

# flake8: noqa

"""
    CoinAPI Indexes REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: support@apibricks.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "IndexesApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ModelsIndexDefinitionSnapshotEntry",
    "ModelsIndexIdentifier",
    "ModelsIndexMultiAssetWeight",
    "ModelsIndexTimeseriesItem",
    "ModelsIndexValue",
    "ModelsIndexValueComponent",
]

# import apis into sdk package
from api_bricks_coinapi_indexes_api_rest.api.indexes_api import IndexesApi as IndexesApi

# import ApiClient
from api_bricks_coinapi_indexes_api_rest.api_response import ApiResponse as ApiResponse
from api_bricks_coinapi_indexes_api_rest.api_client import ApiClient as ApiClient
from api_bricks_coinapi_indexes_api_rest.configuration import Configuration as Configuration
from api_bricks_coinapi_indexes_api_rest.exceptions import OpenApiException as OpenApiException
from api_bricks_coinapi_indexes_api_rest.exceptions import ApiTypeError as ApiTypeError
from api_bricks_coinapi_indexes_api_rest.exceptions import ApiValueError as ApiValueError
from api_bricks_coinapi_indexes_api_rest.exceptions import ApiKeyError as ApiKeyError
from api_bricks_coinapi_indexes_api_rest.exceptions import ApiAttributeError as ApiAttributeError
from api_bricks_coinapi_indexes_api_rest.exceptions import ApiException as ApiException

# import models into sdk package
from api_bricks_coinapi_indexes_api_rest.models.models_index_definition_snapshot_entry import ModelsIndexDefinitionSnapshotEntry as ModelsIndexDefinitionSnapshotEntry
from api_bricks_coinapi_indexes_api_rest.models.models_index_identifier import ModelsIndexIdentifier as ModelsIndexIdentifier
from api_bricks_coinapi_indexes_api_rest.models.models_index_multi_asset_weight import ModelsIndexMultiAssetWeight as ModelsIndexMultiAssetWeight
from api_bricks_coinapi_indexes_api_rest.models.models_index_timeseries_item import ModelsIndexTimeseriesItem as ModelsIndexTimeseriesItem
from api_bricks_coinapi_indexes_api_rest.models.models_index_value import ModelsIndexValue as ModelsIndexValue
from api_bricks_coinapi_indexes_api_rest.models.models_index_value_component import ModelsIndexValueComponent as ModelsIndexValueComponent

