# coding: utf-8

"""
    FinFeedAPI SEC REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: support@apibricks.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api_bricks_sec_api_rest.api.xbrl_converter_api import XbrlConverterApi


class TestXbrlConverterApi(unittest.TestCase):
    """XbrlConverterApi unit test stubs"""

    def setUp(self) -> None:
        self.api = XbrlConverterApi()

    def tearDown(self) -> None:
        pass

    def test_v1_xbrl_converter_get(self) -> None:
        """Test case for v1_xbrl_converter_get

        Convert XBRL data to JSON format
        """
        pass


if __name__ == '__main__':
    unittest.main()
