/**
 * FinFeedAPI Stock REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ModelsDeleteOrderModel model module.
 * @module model/ModelsDeleteOrderModel
 * @version v1
 */
class ModelsDeleteOrderModel {
    /**
     * Constructs a new <code>ModelsDeleteOrderModel</code>.
     * Represents the response DTO for order delete information
     * @alias module:model/ModelsDeleteOrderModel
     */
    constructor() { 
        
        ModelsDeleteOrderModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ModelsDeleteOrderModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModelsDeleteOrderModel} obj Optional instance to populate.
     * @return {module:model/ModelsDeleteOrderModel} The populated <code>ModelsDeleteOrderModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelsDeleteOrderModel();

            if (data.hasOwnProperty('symbol')) {
                obj['symbol'] = ApiClient.convertToType(data['symbol'], 'String');
            }
            if (data.hasOwnProperty('timestamp_nanos')) {
                obj['timestamp_nanos'] = ApiClient.convertToType(data['timestamp_nanos'], 'Number');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Date');
            }
            if (data.hasOwnProperty('order_id_reference')) {
                obj['order_id_reference'] = ApiClient.convertToType(data['order_id_reference'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ModelsDeleteOrderModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ModelsDeleteOrderModel</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['symbol'] && !(typeof data['symbol'] === 'string' || data['symbol'] instanceof String)) {
            throw new Error("Expected the field `symbol` to be a primitive type in the JSON string but got " + data['symbol']);
        }

        return true;
    }


}



/**
 * The stock symbol
 * @member {String} symbol
 */
ModelsDeleteOrderModel.prototype['symbol'] = undefined;

/**
 * Original timestamp in nanoseconds since epoch
 * @member {Number} timestamp_nanos
 */
ModelsDeleteOrderModel.prototype['timestamp_nanos'] = undefined;

/**
 * Time when the order was deleted as DateTime
 * @member {Date} timestamp
 */
ModelsDeleteOrderModel.prototype['timestamp'] = undefined;

/**
 * Order identifier reference
 * @member {Number} order_id_reference
 */
ModelsDeleteOrderModel.prototype['order_id_reference'] = undefined;






export default ModelsDeleteOrderModel;

