/**
 * FinFeedAPI Stock REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OHLCVTimeSeriesTimeseriesItem model module.
 * @module model/OHLCVTimeSeriesTimeseriesItem
 * @version v1
 */
class OHLCVTimeSeriesTimeseriesItem {
    /**
     * Constructs a new <code>OHLCVTimeSeriesTimeseriesItem</code>.
     * Represents a timeseries item with price and volume information.
     * @alias module:model/OHLCVTimeSeriesTimeseriesItem
     */
    constructor() { 
        
        OHLCVTimeSeriesTimeseriesItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OHLCVTimeSeriesTimeseriesItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OHLCVTimeSeriesTimeseriesItem} obj Optional instance to populate.
     * @return {module:model/OHLCVTimeSeriesTimeseriesItem} The populated <code>OHLCVTimeSeriesTimeseriesItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OHLCVTimeSeriesTimeseriesItem();

            if (data.hasOwnProperty('time_period_start')) {
                obj['time_period_start'] = ApiClient.convertToType(data['time_period_start'], 'Date');
            }
            if (data.hasOwnProperty('time_period_end')) {
                obj['time_period_end'] = ApiClient.convertToType(data['time_period_end'], 'Date');
            }
            if (data.hasOwnProperty('time_open')) {
                obj['time_open'] = ApiClient.convertToType(data['time_open'], 'Date');
            }
            if (data.hasOwnProperty('time_close')) {
                obj['time_close'] = ApiClient.convertToType(data['time_close'], 'Date');
            }
            if (data.hasOwnProperty('price_open')) {
                obj['price_open'] = ApiClient.convertToType(data['price_open'], 'Number');
            }
            if (data.hasOwnProperty('price_high')) {
                obj['price_high'] = ApiClient.convertToType(data['price_high'], 'Number');
            }
            if (data.hasOwnProperty('price_low')) {
                obj['price_low'] = ApiClient.convertToType(data['price_low'], 'Number');
            }
            if (data.hasOwnProperty('price_close')) {
                obj['price_close'] = ApiClient.convertToType(data['price_close'], 'Number');
            }
            if (data.hasOwnProperty('volume_traded')) {
                obj['volume_traded'] = ApiClient.convertToType(data['volume_traded'], 'Number');
            }
            if (data.hasOwnProperty('trades_count')) {
                obj['trades_count'] = ApiClient.convertToType(data['trades_count'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OHLCVTimeSeriesTimeseriesItem</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OHLCVTimeSeriesTimeseriesItem</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Gets or sets the start time of the time period.
 * @member {Date} time_period_start
 */
OHLCVTimeSeriesTimeseriesItem.prototype['time_period_start'] = undefined;

/**
 * Gets or sets the end time of the time period.
 * @member {Date} time_period_end
 */
OHLCVTimeSeriesTimeseriesItem.prototype['time_period_end'] = undefined;

/**
 * Gets or sets the time when the price opened.
 * @member {Date} time_open
 */
OHLCVTimeSeriesTimeseriesItem.prototype['time_open'] = undefined;

/**
 * Gets or sets the time when the price closed.
 * @member {Date} time_close
 */
OHLCVTimeSeriesTimeseriesItem.prototype['time_close'] = undefined;

/**
 * Gets or sets the opening price.
 * @member {Number} price_open
 */
OHLCVTimeSeriesTimeseriesItem.prototype['price_open'] = undefined;

/**
 * Gets or sets the highest price during the time period.
 * @member {Number} price_high
 */
OHLCVTimeSeriesTimeseriesItem.prototype['price_high'] = undefined;

/**
 * Gets or sets the lowest price during the time period.
 * @member {Number} price_low
 */
OHLCVTimeSeriesTimeseriesItem.prototype['price_low'] = undefined;

/**
 * Gets or sets the closing price.
 * @member {Number} price_close
 */
OHLCVTimeSeriesTimeseriesItem.prototype['price_close'] = undefined;

/**
 * Gets or sets the total volume traded during the time period.
 * @member {Number} volume_traded
 */
OHLCVTimeSeriesTimeseriesItem.prototype['volume_traded'] = undefined;

/**
 * Gets or sets the number of trades executed during the time period.
 * @member {Number} trades_count
 */
OHLCVTimeSeriesTimeseriesItem.prototype['trades_count'] = undefined;






export default OHLCVTimeSeriesTimeseriesItem;

