{-
   FinFeedAPI Currencies Realtime REST API

   No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

   OpenAPI Version: 3.0.4
   FinFeedAPI Currencies Realtime REST API API version: v1
   Contact: support@apibricks.io
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : FinFeedAPICurrenciesRealtimeREST.Logging
Logging functions
-}
{-# LANGUAGE CPP #-}

#ifdef USE_KATIP

module FinFeedAPICurrenciesRealtimeREST.Logging
  ( module FinFeedAPICurrenciesRealtimeREST.LoggingKatip
  ) where

import FinFeedAPICurrenciesRealtimeREST.LoggingKatip

#else

module FinFeedAPICurrenciesRealtimeREST.Logging
  ( module FinFeedAPICurrenciesRealtimeREST.LoggingMonadLogger
  ) where

import FinFeedAPICurrenciesRealtimeREST.LoggingMonadLogger

#endif
