export * from './DownloadApi';
import { DownloadApi } from './DownloadApi';
export * from './ExtractorApi';
import { ExtractorApi } from './ExtractorApi';
export * from './FilingsApi';
import { FilingsApi } from './FilingsApi';
export * from './FullTextApi';
import { FullTextApi } from './FullTextApi';
export * from './XbrlConverterApi';
import { XbrlConverterApi } from './XbrlConverterApi';
export const APIS = [DownloadApi, ExtractorApi, FilingsApi, FullTextApi, XbrlConverterApi];
