export * from './DownloadApi';
import { DownloadApi } from './DownloadApi';
export * from './ExtractorApi';
import { ExtractorApi } from './ExtractorApi';
export * from './FilingsApi';
import { FilingsApi } from './FilingsApi';
export * from './FullTextApi';
import { FullTextApi } from './FullTextApi';
export * from './XBRLConverterApi';
import { XBRLConverterApi } from './XBRLConverterApi';
export const APIS = [DownloadApi, ExtractorApi, FilingsApi, FullTextApi, XBRLConverterApi];
