/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents the last executed transaction.
 *
 * @param timeExchange Gets or sets the exchange time of the last trade.
 * @param timeCoinapi Gets or sets the CoinAPI time when the last trade was received.
 * @param uuid Gets or sets the UUID of the last trade.
 * @param price Gets or sets the price of the last trade.
 * @param propertySize Gets or sets the size of the last trade.
 * @param takerSide Gets or sets the taker side of the last trade.
 */


data class V1LastTrade (

    /* Gets or sets the exchange time of the last trade. */
    @Json(name = "time_exchange")
    val timeExchange: java.time.OffsetDateTime? = null,

    /* Gets or sets the CoinAPI time when the last trade was received. */
    @Json(name = "time_coinapi")
    val timeCoinapi: java.time.OffsetDateTime? = null,

    /* Gets or sets the UUID of the last trade. */
    @Json(name = "uuid")
    val uuid: java.util.UUID? = null,

    /* Gets or sets the price of the last trade. */
    @Json(name = "price")
    val price: kotlin.Double? = null,

    /* Gets or sets the size of the last trade. */
    @Json(name = "size")
    val propertySize: kotlin.Double? = null,

    /* Gets or sets the taker side of the last trade. */
    @Json(name = "taker_side")
    val takerSide: kotlin.String? = null

) {


}

