/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents a metric information.
 *
 * @param metricId Gets or sets the metric identifier.
 * @param description Gets or sets the description of the metric.
 * @param sourceId Gets or sets the source identifier of the metric.
 */


data class V1MetricInfo (

    /* Gets or sets the metric identifier. */
    @Json(name = "metric_id")
    val metricId: kotlin.String? = null,

    /* Gets or sets the description of the metric. */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Gets or sets the source identifier of the metric. */
    @Json(name = "source_id")
    val sourceId: kotlin.String? = null

) {


}

