/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents a symbol data model.
 *
 * @param symbolId Gets or sets the symbol identifier.
 * @param exchangeId Gets or sets the exchange identifier.
 * @param symbolType Gets or sets the symbol type.
 * @param assetIdBase Gets or sets the base asset identifier.
 * @param assetIdQuote Gets or sets the quote asset identifier.
 * @param assetIdUnit Gets or sets the unit asset identifier.
 * @param futureContractUnit Gets or sets the contract unit for futures.
 * @param futureContractUnitAsset Gets or sets the asset used as the unit for futures contract.
 * @param futureDeliveryTime Gets or sets the future delivery time for futures contract.
 * @param optionTypeIsCall Gets or sets a value indicating whether the option type is a call.
 * @param optionStrikePrice Gets or sets the strike price for options.
 * @param optionContractUnit Gets or sets the contract unit for options.
 * @param optionExerciseStyle Gets or sets the exercise style for options. Possible values: AMERICAN, ASIAN, BARRIER, BERMUDAN, BINARY, EUROPEAN, EXOTIC.
 * @param optionExpirationTime Gets or sets the expiration time for options.
 * @param contractDeliveryTime Gets or sets the delivery time for contracts.
 * @param contractUnit Gets or sets the contract unit for contracts.
 * @param contractUnitAsset Gets or sets the asset used as the unit for contracts.
 * @param contractId Gets or sets the contract identifier.
 * @param contractDisplayName Gets or sets the display name of the contract.
 * @param contractDisplayDescription Gets or sets the display description of the contract.
 * @param dataStart Gets the start date of the data in string format (\"yyyy-MM-dd\").
 * @param dataEnd Gets the end date of the data in string format (\"yyyy-MM-dd\").
 * @param dataQuoteStart Gets or sets the start date of quote data.
 * @param dataQuoteEnd Gets or sets the end date of quote data.
 * @param dataOrderbookStart Gets or sets the start date of order book data.
 * @param dataOrderbookEnd Gets or sets the end date of order book data.
 * @param dataTradeStart Gets or sets the start date of trade data.
 * @param dataTradeEnd Gets or sets the end date of trade data.
 * @param indexId Gets or sets the index identifier.
 * @param indexDisplayName Gets or sets the display name of the index.
 * @param indexDisplayDescription Gets or sets the display description of the index.
 * @param volume1hrs Gets or sets the volume in the last 1 hour.
 * @param volume1hrsUsd Gets or sets the volume in USD in the last 1 hour.
 * @param volume1day Gets or sets the volume in the last 1 day.
 * @param volume1dayUsd Gets or sets the volume in USD in the last 1 day.
 * @param volume1mth Gets or sets the volume in the last 1 month.
 * @param volume1mthUsd Gets or sets the volume in USD in the last 1 month.
 * @param price Gets or sets the price.
 * @param symbolIdExchange Gets or sets the symbol identifier in the exchange.
 * @param assetIdBaseExchange Gets or sets the base asset identifier in the exchange.
 * @param assetIdQuoteExchange Gets or sets the quote asset identifier in the exchange.
 * @param pricePrecision Gets or sets the price precision.
 * @param sizePrecision Gets or sets the size precision.
 * @param rawKvp Key Value Pair store with raw data from the data source.
 * @param futureIsInverse Gets or sets a value indicating whether the futures contract is inverse (coin-margined).
 * @param futureIsQuanto Gets or sets a value indicating whether the futures contract is quanto.
 * @param volumeToUsd Gets or sets the volume in USD.
 * @param optionBarrierUpPrice Gets or sets the up barrier price for barrier options.
 * @param optionBarrierUpType Gets or sets the up barrier type for barrier options. Possible values: EXPIRATION, IN, OUT.
 * @param optionBarrierDownPrice Gets or sets the down barrier price for barrier options.
 * @param optionBarrierDownType Gets or sets the down barrier type for barrier options. Possible values: EXPIRATION, IN, OUT.
 * @param symbolIdInt Gets or sets the symbol identifier in integer immutable format, used to correlate data across different APIs.
 */


data class V1Symbol (

    /* Gets or sets the symbol identifier. */
    @Json(name = "symbol_id")
    val symbolId: kotlin.String? = null,

    /* Gets or sets the exchange identifier. */
    @Json(name = "exchange_id")
    val exchangeId: kotlin.String? = null,

    /* Gets or sets the symbol type. */
    @Json(name = "symbol_type")
    val symbolType: kotlin.String? = null,

    /* Gets or sets the base asset identifier. */
    @Json(name = "asset_id_base")
    val assetIdBase: kotlin.String? = null,

    /* Gets or sets the quote asset identifier. */
    @Json(name = "asset_id_quote")
    val assetIdQuote: kotlin.String? = null,

    /* Gets or sets the unit asset identifier. */
    @Json(name = "asset_id_unit")
    val assetIdUnit: kotlin.String? = null,

    /* Gets or sets the contract unit for futures. */
    @Json(name = "future_contract_unit")
    val futureContractUnit: kotlin.Double? = null,

    /* Gets or sets the asset used as the unit for futures contract. */
    @Json(name = "future_contract_unit_asset")
    val futureContractUnitAsset: kotlin.String? = null,

    /* Gets or sets the future delivery time for futures contract. */
    @Json(name = "future_delivery_time")
    val futureDeliveryTime: java.time.OffsetDateTime? = null,

    /* Gets or sets a value indicating whether the option type is a call. */
    @Json(name = "option_type_is_call")
    val optionTypeIsCall: kotlin.Boolean? = null,

    /* Gets or sets the strike price for options. */
    @Json(name = "option_strike_price")
    val optionStrikePrice: kotlin.Double? = null,

    /* Gets or sets the contract unit for options. */
    @Json(name = "option_contract_unit")
    val optionContractUnit: kotlin.Double? = null,

    /* Gets or sets the exercise style for options. Possible values: AMERICAN, ASIAN, BARRIER, BERMUDAN, BINARY, EUROPEAN, EXOTIC. */
    @Json(name = "option_exercise_style")
    val optionExerciseStyle: kotlin.String? = null,

    /* Gets or sets the expiration time for options. */
    @Json(name = "option_expiration_time")
    val optionExpirationTime: java.time.OffsetDateTime? = null,

    /* Gets or sets the delivery time for contracts. */
    @Json(name = "contract_delivery_time")
    val contractDeliveryTime: java.time.OffsetDateTime? = null,

    /* Gets or sets the contract unit for contracts. */
    @Json(name = "contract_unit")
    val contractUnit: kotlin.Double? = null,

    /* Gets or sets the asset used as the unit for contracts. */
    @Json(name = "contract_unit_asset")
    val contractUnitAsset: kotlin.String? = null,

    /* Gets or sets the contract identifier. */
    @Json(name = "contract_id")
    val contractId: kotlin.String? = null,

    /* Gets or sets the display name of the contract. */
    @Json(name = "contract_display_name")
    val contractDisplayName: kotlin.String? = null,

    /* Gets or sets the display description of the contract. */
    @Json(name = "contract_display_description")
    val contractDisplayDescription: kotlin.String? = null,

    /* Gets the start date of the data in string format (\"yyyy-MM-dd\"). */
    @Json(name = "data_start")
    val dataStart: kotlin.String? = null,

    /* Gets the end date of the data in string format (\"yyyy-MM-dd\"). */
    @Json(name = "data_end")
    val dataEnd: kotlin.String? = null,

    /* Gets or sets the start date of quote data. */
    @Json(name = "data_quote_start")
    val dataQuoteStart: java.time.OffsetDateTime? = null,

    /* Gets or sets the end date of quote data. */
    @Json(name = "data_quote_end")
    val dataQuoteEnd: java.time.OffsetDateTime? = null,

    /* Gets or sets the start date of order book data. */
    @Json(name = "data_orderbook_start")
    val dataOrderbookStart: java.time.OffsetDateTime? = null,

    /* Gets or sets the end date of order book data. */
    @Json(name = "data_orderbook_end")
    val dataOrderbookEnd: java.time.OffsetDateTime? = null,

    /* Gets or sets the start date of trade data. */
    @Json(name = "data_trade_start")
    val dataTradeStart: java.time.OffsetDateTime? = null,

    /* Gets or sets the end date of trade data. */
    @Json(name = "data_trade_end")
    val dataTradeEnd: java.time.OffsetDateTime? = null,

    /* Gets or sets the index identifier. */
    @Json(name = "index_id")
    val indexId: kotlin.String? = null,

    /* Gets or sets the display name of the index. */
    @Json(name = "index_display_name")
    val indexDisplayName: kotlin.String? = null,

    /* Gets or sets the display description of the index. */
    @Json(name = "index_display_description")
    val indexDisplayDescription: kotlin.String? = null,

    /* Gets or sets the volume in the last 1 hour. */
    @Json(name = "volume_1hrs")
    val volume1hrs: kotlin.Double? = null,

    /* Gets or sets the volume in USD in the last 1 hour. */
    @Json(name = "volume_1hrs_usd")
    val volume1hrsUsd: kotlin.Double? = null,

    /* Gets or sets the volume in the last 1 day. */
    @Json(name = "volume_1day")
    val volume1day: kotlin.Double? = null,

    /* Gets or sets the volume in USD in the last 1 day. */
    @Json(name = "volume_1day_usd")
    val volume1dayUsd: kotlin.Double? = null,

    /* Gets or sets the volume in the last 1 month. */
    @Json(name = "volume_1mth")
    val volume1mth: kotlin.Double? = null,

    /* Gets or sets the volume in USD in the last 1 month. */
    @Json(name = "volume_1mth_usd")
    val volume1mthUsd: kotlin.Double? = null,

    /* Gets or sets the price. */
    @Json(name = "price")
    val price: kotlin.Double? = null,

    /* Gets or sets the symbol identifier in the exchange. */
    @Json(name = "symbol_id_exchange")
    val symbolIdExchange: kotlin.String? = null,

    /* Gets or sets the base asset identifier in the exchange. */
    @Json(name = "asset_id_base_exchange")
    val assetIdBaseExchange: kotlin.String? = null,

    /* Gets or sets the quote asset identifier in the exchange. */
    @Json(name = "asset_id_quote_exchange")
    val assetIdQuoteExchange: kotlin.String? = null,

    /* Gets or sets the price precision. */
    @Json(name = "price_precision")
    val pricePrecision: kotlin.Double? = null,

    /* Gets or sets the size precision. */
    @Json(name = "size_precision")
    val sizePrecision: kotlin.Double? = null,

    /* Key Value Pair store with raw data from the data source. */
    @Json(name = "raw_kvp")
    val rawKvp: kotlin.collections.Map<kotlin.String, kotlin.String?>? = null,

    /* Gets or sets a value indicating whether the futures contract is inverse (coin-margined). */
    @Json(name = "future_is_inverse")
    val futureIsInverse: kotlin.Boolean? = null,

    /* Gets or sets a value indicating whether the futures contract is quanto. */
    @Json(name = "future_is_quanto")
    val futureIsQuanto: kotlin.Boolean? = null,

    /* Gets or sets the volume in USD. */
    @Json(name = "volume_to_usd")
    val volumeToUsd: kotlin.Double? = null,

    /* Gets or sets the up barrier price for barrier options. */
    @Json(name = "option_barrier_up_price")
    val optionBarrierUpPrice: kotlin.Double? = null,

    /* Gets or sets the up barrier type for barrier options. Possible values: EXPIRATION, IN, OUT. */
    @Json(name = "option_barrier_up_type")
    val optionBarrierUpType: kotlin.String? = null,

    /* Gets or sets the down barrier price for barrier options. */
    @Json(name = "option_barrier_down_price")
    val optionBarrierDownPrice: kotlin.Double? = null,

    /* Gets or sets the down barrier type for barrier options. Possible values: EXPIRATION, IN, OUT. */
    @Json(name = "option_barrier_down_type")
    val optionBarrierDownType: kotlin.String? = null,

    /* Gets or sets the symbol identifier in integer immutable format, used to correlate data across different APIs. */
    @Json(name = "symbol_id_int")
    val symbolIdInt: kotlin.Int? = null

) {


}

