/*
 * CoinAPI Indexes REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using APIBricks.CoinAPI.IndexesAPI.REST.V1.Model;
using APIBricks.CoinAPI.IndexesAPI.REST.V1.Client;
using System.Reflection;

namespace APIBricks.CoinAPI.IndexesAPI.REST.V1.Test.Model
{
    /// <summary>
    ///  Class for testing ModelsIndexIdentifier
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ModelsIndexIdentifierTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ModelsIndexIdentifier
        //private ModelsIndexIdentifier instance;

        public ModelsIndexIdentifierTests()
        {
            // TODO uncomment below to create an instance of ModelsIndexIdentifier
            //instance = new ModelsIndexIdentifier();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ModelsIndexIdentifier
        /// </summary>
        [Fact]
        public void ModelsIndexIdentifierInstanceTest()
        {
            // TODO uncomment below to test "IsType" ModelsIndexIdentifier
            //Assert.IsType<ModelsIndexIdentifier>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
    }
}
