#
# CoinAPI Market Data REST API
# Cryptocurrency market data: metadata, quotes, books, trades, OHLCV, rates, metrics, options.
# Version: v1
# Contact: support@apibricks.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'OptionsApi' {
    Context 'Invoke-V1OptionsExchangeIdCurrentGet' {
        It 'Test Invoke-V1OptionsExchangeIdCurrentGet' {
            #$TestResult = Invoke-V1OptionsExchangeIdCurrentGet -ExchangeId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
