/**
 * CoinAPI Indexes REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.21.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Models_Exchange.h
 *
 * Represents an exchange.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Models_Exchange_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Models_Exchange_H_

#include <boost/optional.hpp>

#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// Represents an exchange.
/// </summary>
class  Models_Exchange
    : public ModelBase
{
public:
    Models_Exchange();
    virtual ~Models_Exchange();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Models_Exchange members


    /// <summary>
    /// Gets or sets the exchange ID.
    /// </summary>
    utility::string_t getExchangeId() const;
    bool exchangeIdIsSet() const;
    void unsetExchange_id();
    void setExchangeId(const utility::string_t& value);

    /// <summary>
    /// Gets or sets the website URL of the exchange.
    /// </summary>
    utility::string_t getWebsite() const;
    bool websiteIsSet() const;
    void unsetWebsite();
    void setWebsite(const utility::string_t& value);

    /// <summary>
    /// Gets or sets the name of the exchange.
    /// </summary>
    utility::string_t getName() const;
    bool nameIsSet() const;
    void unsetName();
    void setName(const utility::string_t& value);


protected:
    boost::optional<utility::string_t> m_Exchange_id;

    boost::optional<utility::string_t> m_Website;

    boost::optional<utility::string_t> m_Name;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Models_Exchange_H_ */
