/*
 * CoinAPI Indexes REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Represents a timeseries item with value information.
 **/
@ApiModel(description = "Represents a timeseries item with value information.")
public class ModelsIndexTimeseriesItem {
  
  @SerializedName("time_period_start")
  private Date timePeriodStart = null;
  @SerializedName("time_period_end")
  private Date timePeriodEnd = null;
  @SerializedName("time_open")
  private Date timeOpen = null;
  @SerializedName("time_close")
  private Date timeClose = null;
  @SerializedName("value_open")
  private Double valueOpen = null;
  @SerializedName("value_high")
  private Double valueHigh = null;
  @SerializedName("value_low")
  private Double valueLow = null;
  @SerializedName("value_close")
  private Double valueClose = null;
  @SerializedName("value_count")
  private Long valueCount = null;

  /**
   * Gets or sets the start time of the time period.
   **/
  @ApiModelProperty(value = "Gets or sets the start time of the time period.")
  public Date getTimePeriodStart() {
    return timePeriodStart;
  }
  public void setTimePeriodStart(Date timePeriodStart) {
    this.timePeriodStart = timePeriodStart;
  }

  /**
   * Gets or sets the end time of the time period.
   **/
  @ApiModelProperty(value = "Gets or sets the end time of the time period.")
  public Date getTimePeriodEnd() {
    return timePeriodEnd;
  }
  public void setTimePeriodEnd(Date timePeriodEnd) {
    this.timePeriodEnd = timePeriodEnd;
  }

  /**
   * Gets or sets the time when the value opened.
   **/
  @ApiModelProperty(value = "Gets or sets the time when the value opened.")
  public Date getTimeOpen() {
    return timeOpen;
  }
  public void setTimeOpen(Date timeOpen) {
    this.timeOpen = timeOpen;
  }

  /**
   * Gets or sets the time when the value closed.
   **/
  @ApiModelProperty(value = "Gets or sets the time when the value closed.")
  public Date getTimeClose() {
    return timeClose;
  }
  public void setTimeClose(Date timeClose) {
    this.timeClose = timeClose;
  }

  /**
   * Gets or sets the opening value.
   **/
  @ApiModelProperty(value = "Gets or sets the opening value.")
  public Double getValueOpen() {
    return valueOpen;
  }
  public void setValueOpen(Double valueOpen) {
    this.valueOpen = valueOpen;
  }

  /**
   * Gets or sets the highest value during the time period.
   **/
  @ApiModelProperty(value = "Gets or sets the highest value during the time period.")
  public Double getValueHigh() {
    return valueHigh;
  }
  public void setValueHigh(Double valueHigh) {
    this.valueHigh = valueHigh;
  }

  /**
   * Gets or sets the lowest value during the time period.
   **/
  @ApiModelProperty(value = "Gets or sets the lowest value during the time period.")
  public Double getValueLow() {
    return valueLow;
  }
  public void setValueLow(Double valueLow) {
    this.valueLow = valueLow;
  }

  /**
   * Gets or sets the closing value.
   **/
  @ApiModelProperty(value = "Gets or sets the closing value.")
  public Double getValueClose() {
    return valueClose;
  }
  public void setValueClose(Double valueClose) {
    this.valueClose = valueClose;
  }

  /**
   * Gets or sets the number of values during the time period.
   **/
  @ApiModelProperty(value = "Gets or sets the number of values during the time period.")
  public Long getValueCount() {
    return valueCount;
  }
  public void setValueCount(Long valueCount) {
    this.valueCount = valueCount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelsIndexTimeseriesItem modelsIndexTimeseriesItem = (ModelsIndexTimeseriesItem) o;
    return (this.timePeriodStart == null ? modelsIndexTimeseriesItem.timePeriodStart == null : this.timePeriodStart.equals(modelsIndexTimeseriesItem.timePeriodStart)) &&
        (this.timePeriodEnd == null ? modelsIndexTimeseriesItem.timePeriodEnd == null : this.timePeriodEnd.equals(modelsIndexTimeseriesItem.timePeriodEnd)) &&
        (this.timeOpen == null ? modelsIndexTimeseriesItem.timeOpen == null : this.timeOpen.equals(modelsIndexTimeseriesItem.timeOpen)) &&
        (this.timeClose == null ? modelsIndexTimeseriesItem.timeClose == null : this.timeClose.equals(modelsIndexTimeseriesItem.timeClose)) &&
        (this.valueOpen == null ? modelsIndexTimeseriesItem.valueOpen == null : this.valueOpen.equals(modelsIndexTimeseriesItem.valueOpen)) &&
        (this.valueHigh == null ? modelsIndexTimeseriesItem.valueHigh == null : this.valueHigh.equals(modelsIndexTimeseriesItem.valueHigh)) &&
        (this.valueLow == null ? modelsIndexTimeseriesItem.valueLow == null : this.valueLow.equals(modelsIndexTimeseriesItem.valueLow)) &&
        (this.valueClose == null ? modelsIndexTimeseriesItem.valueClose == null : this.valueClose.equals(modelsIndexTimeseriesItem.valueClose)) &&
        (this.valueCount == null ? modelsIndexTimeseriesItem.valueCount == null : this.valueCount.equals(modelsIndexTimeseriesItem.valueCount));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.timePeriodStart == null ? 0: this.timePeriodStart.hashCode());
    result = 31 * result + (this.timePeriodEnd == null ? 0: this.timePeriodEnd.hashCode());
    result = 31 * result + (this.timeOpen == null ? 0: this.timeOpen.hashCode());
    result = 31 * result + (this.timeClose == null ? 0: this.timeClose.hashCode());
    result = 31 * result + (this.valueOpen == null ? 0: this.valueOpen.hashCode());
    result = 31 * result + (this.valueHigh == null ? 0: this.valueHigh.hashCode());
    result = 31 * result + (this.valueLow == null ? 0: this.valueLow.hashCode());
    result = 31 * result + (this.valueClose == null ? 0: this.valueClose.hashCode());
    result = 31 * result + (this.valueCount == null ? 0: this.valueCount.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelsIndexTimeseriesItem {\n");
    
    sb.append("  timePeriodStart: ").append(timePeriodStart).append("\n");
    sb.append("  timePeriodEnd: ").append(timePeriodEnd).append("\n");
    sb.append("  timeOpen: ").append(timeOpen).append("\n");
    sb.append("  timeClose: ").append(timeClose).append("\n");
    sb.append("  valueOpen: ").append(valueOpen).append("\n");
    sb.append("  valueHigh: ").append(valueHigh).append("\n");
    sb.append("  valueLow: ").append(valueLow).append("\n");
    sb.append("  valueClose: ").append(valueClose).append("\n");
    sb.append("  valueCount: ").append(valueCount).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
