/**
 * CoinAPI Indexes REST API
 *
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelsIndexValueComponent } from './modelsIndexValueComponent';


export interface ModelsIndexValue { 
    timestamp?: string;
    value?: number;
    composition?: Array<ModelsIndexValueComponent> | null;
}

