{-
   FX Realtime REST API

   No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

   OpenAPI Version: 3.0.4
   FX Realtime REST API API version: v1
   Contact: support@apibricks.io
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : FXRealtimeREST.API.RateLimit
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module FXRealtimeREST.API.RateLimit where

import FXRealtimeREST.Core
import FXRealtimeREST.MimeTypes
import FXRealtimeREST.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** RateLimit

-- *** internalRatelimitWsconconApikeyGet

-- | @GET \/internal\/ratelimit\/wsconcon\/apikey@
-- 
-- AuthMethod: 'AuthApiKeyAPIKey', 'AuthBasicJWT'
-- 
internalRatelimitWsconconApikeyGet
  :: FXRealtimeRESTRequest InternalRatelimitWsconconApikeyGet MimeNoContent NoContent MimeNoContent
internalRatelimitWsconconApikeyGet =
  _mkRequest "GET" ["/internal/ratelimit/wsconcon/apikey"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthApiKeyAPIKey)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicJWT)

data InternalRatelimitWsconconApikeyGet  
instance Produces InternalRatelimitWsconconApikeyGet MimeNoContent


-- *** internalRatelimitWshelloIpGet

-- | @GET \/internal\/ratelimit\/wshello\/ip@
-- 
-- AuthMethod: 'AuthApiKeyAPIKey', 'AuthBasicJWT'
-- 
internalRatelimitWshelloIpGet
  :: FXRealtimeRESTRequest InternalRatelimitWshelloIpGet MimeNoContent NoContent MimeNoContent
internalRatelimitWshelloIpGet =
  _mkRequest "GET" ["/internal/ratelimit/wshello/ip"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthApiKeyAPIKey)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicJWT)

data InternalRatelimitWshelloIpGet  
instance Produces InternalRatelimitWshelloIpGet MimeNoContent


-- *** internalRatelimitWsreqIpGet

-- | @GET \/internal\/ratelimit\/wsreq\/ip@
-- 
-- AuthMethod: 'AuthApiKeyAPIKey', 'AuthBasicJWT'
-- 
internalRatelimitWsreqIpGet
  :: FXRealtimeRESTRequest InternalRatelimitWsreqIpGet MimeNoContent NoContent MimeNoContent
internalRatelimitWsreqIpGet =
  _mkRequest "GET" ["/internal/ratelimit/wsreq/ip"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthApiKeyAPIKey)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicJWT)

data InternalRatelimitWsreqIpGet  
instance Produces InternalRatelimitWsreqIpGet MimeNoContent

