/**
 * CoinAPI Market Data REST API
 *
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents a listing data item.
 */
export interface V1ListingItem { 
    /**
     * Gets or sets the metric ID.
     */
    metric_id?: string | null;
    /**
     * Gets or sets the CoinAPI symbol ID. Null for exchange-level metrics.
     */
    symbol_id?: string | null;
    /**
     * Gets or sets the exchange-native symbol ID. Null for exchange-level metrics.
     */
    symbol_id_external?: string | null;
    /**
     * Gets or sets the exchange ID.
     */
    exchange_id?: string | null;
    /**
     * Gets or sets the asset ID.
     */
    asset_id?: string | null;
    /**
     * Gets or sets the asset ID.
     */
    asset_id_external?: string | null;
    /**
     * Gets or sets the chain ID.
     */
    chain_id?: string | null;
    /**
     * Gets or sets the network ID.
     */
    network_id?: string | null;
}

