/**
 * CoinAPI Market Data REST API
 *
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { V1Strike } from './v1Strike';


/**
 * Represents an option exchange group data model.
 */
export interface V1OptionExchangeGroup { 
    /**
     * Gets or sets the base asset identifier.
     */
    asset_id_base?: string | null;
    /**
     * Gets or sets the quote asset identifier.
     */
    asset_id_quote?: string | null;
    /**
     * Gets or sets the underlying price of the option.
     */
    underlying_price?: number | null;
    /**
     * Gets or sets the expiration time of the option.
     */
    time_expiration?: string;
    /**
     * Gets or sets the list of strikes available.
     */
    strikes?: Array<V1Strike> | null;
}

