/**
 * CoinAPI Market Data REST API
 *
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents the depth of an order book.
 */
export interface V1OrderBookDepth { 
    /**
     * Gets or sets the symbol identifier.
     */
    symbol_id?: string | null;
    /**
     * Gets or sets the exchange time of the order book.
     */
    time_exchange?: string;
    /**
     * Gets or sets the CoinAPI time when the order book was received.
     */
    time_coinapi?: string;
    /**
     * Gets or sets the number of ask levels in the order book.
     */
    ask_levels?: number;
    /**
     * Gets or sets the number of bid levels in the order book.
     */
    bid_levels?: number;
    /**
     * Gets or sets the depth of the ask side of the order book.
     */
    ask_depth?: number;
    /**
     * Gets or sets the depth of the bid side of the order book.
     */
    bid_depth?: number;
}

