/**
 * CoinAPI Market Data REST API
 *
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents symbol mapping information for exchange symbols.
 */
export interface V1SymbolMapping { 
    /**
     * Gets or sets the symbol ID.
     */
    symbol_id?: string | null;
    /**
     * Gets or sets the exchange-specific symbol ID.
     */
    symbol_id_exchange?: string | null;
    /**
     * Gets or sets the DataInfo ID.
     */
    coinapi_datainfo_id?: number;
    /**
     * Gets or sets the exchange-specific base asset ID.
     */
    asset_id_base_exchange?: string | null;
    /**
     * Gets or sets the exchange-specific quote asset ID.
     */
    asset_id_quote_exchange?: string | null;
    /**
     * Gets or sets the base asset ID.
     */
    asset_id_base?: string | null;
    /**
     * Gets or sets the quote asset ID.
     */
    asset_id_quote?: string | null;
    /**
     * Gets or sets the price precision.
     */
    price_precision?: number | null;
    /**
     * Gets or sets the size precision.
     */
    size_precision?: number | null;
}

