/**
 * @fileoverview AUTOMATICALLY GENERATED service for API.Client.IndexInputDataApi.
 * Do not edit this file by hand or your changes will be lost next time it is
 * generated.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * Version: v1
* Generator version: 7.21.0
 * Generated by: org.openapitools.codegen.languages.JavascriptClosureAngularClientCodegen
 */
/**
 * @license MIT License
 * https://github.com/api-bricks/api-bricks-sdk/blob/master/LICENSE
 */

goog.provide('API.Client.IndexInputDataApi');

goog.require('API.Client.Models.IndexDefinitionInputData');
goog.require('API.Client.Models.IndexDefinitionSnapshotEntry');

/**
 * @constructor
 * @param {!angular.$http} $http
 * @param {!Object} $httpParamSerializer
 * @param {!angular.$injector} $injector
 * @struct
 */
API.Client.IndexInputDataApi = function($http, $httpParamSerializer, $injector) {
  /** @private {!string} */
  this.basePath_ = $injector.has('IndexInputDataApiBasePath') ?
                   /** @type {!string} */ ($injector.get('IndexInputDataApiBasePath')) :
                   'https://rest-api.indexes.coinapi.io';

  /** @private {!Object<string, string>} */
  this.defaultHeaders_ = $injector.has('IndexInputDataApiDefaultHeaders') ?
                   /** @type {!Object<string, string>} */ (
                       $injector.get('IndexInputDataApiDefaultHeaders')) :
                   {};

  /** @private {!angular.$http} */
  this.http_ = $http;

  /** @package {!Object} */
  this.httpParamSerializer = $injector.get('$httpParamSerializer');
}
API.Client.IndexInputDataApi.$inject = ['$http', '$httpParamSerializer', '$injector'];

/**
 * Returns all data inputs for a specific index definition
 * 
 * @param {!string} indexDefinitionId 
 * @param {!angular.$http.Config=} opt_extraHttpRequestParams Extra HTTP parameters to send.
 * @return {!angular.$q.Promise<!Array<!API.Client.Models.IndexDefinitionInputData>>}
 */
API.Client.IndexInputDataApi.prototype.v1IndexdefInputDataIndexDefinitionIdAllGet = function(indexDefinitionId, opt_extraHttpRequestParams) {
  /** @const {string} */
  var path = this.basePath_ + '/v1/indexdef/input-data/{index_definition_id}/all'
      .replace('{' + 'index_definition_id' + '}', String(indexDefinitionId));

  /** @type {!Object} */
  var queryParameters = {};

  /** @type {!Object} */
  var headerParams = angular.extend({}, this.defaultHeaders_);
  // verify required parameter 'indexDefinitionId' is set
  if (!indexDefinitionId) {
    throw new Error('Missing required parameter indexDefinitionId when calling v1IndexdefInputDataIndexDefinitionIdAllGet');
  }
  /** @type {!Object} */
  var httpRequestParams = {
    method: 'GET',
    url: path,
    json: true,
            params: queryParameters,
    headers: headerParams
  };

  if (opt_extraHttpRequestParams) {
    httpRequestParams = angular.extend(httpRequestParams, opt_extraHttpRequestParams);
  }

  return (/** @type {?} */ (this.http_))(httpRequestParams);
}

/**
 * Returns data inputs for certain index definition and time
 * 
 * @param {!string} indexDefinitionId 
 * @param {!Date=} opt_time 
 * @param {!boolean=} opt_enabledOnly 
 * @param {!boolean=} opt_pendingOnly 
 * @param {!string=} opt_filterAssetId 
 * @param {!boolean=} opt_withStatusInfo 
 * @param {!angular.$http.Config=} opt_extraHttpRequestParams Extra HTTP parameters to send.
 * @return {!angular.$q.Promise<!Array<!API.Client.Models.IndexDefinitionSnapshotEntry>>}
 */
API.Client.IndexInputDataApi.prototype.v1IndexdefInputDataIndexDefinitionIdGet = function(indexDefinitionId, opt_time, opt_enabledOnly, opt_pendingOnly, opt_filterAssetId, opt_withStatusInfo, opt_extraHttpRequestParams) {
  /** @const {string} */
  var path = this.basePath_ + '/v1/indexdef/input-data/{index_definition_id}'
      .replace('{' + 'index_definition_id' + '}', String(indexDefinitionId));

  /** @type {!Object} */
  var queryParameters = {};

  /** @type {!Object} */
  var headerParams = angular.extend({}, this.defaultHeaders_);
  // verify required parameter 'indexDefinitionId' is set
  if (!indexDefinitionId) {
    throw new Error('Missing required parameter indexDefinitionId when calling v1IndexdefInputDataIndexDefinitionIdGet');
  }
  if (opt_time !== undefined) {
    queryParameters['time'] = opt_time;
  }

  if (opt_enabledOnly !== undefined) {
    queryParameters['enabled_only'] = opt_enabledOnly;
  }

  if (opt_pendingOnly !== undefined) {
    queryParameters['pending_only'] = opt_pendingOnly;
  }

  if (opt_filterAssetId !== undefined) {
    queryParameters['filter_asset_id'] = opt_filterAssetId;
  }

  if (opt_withStatusInfo !== undefined) {
    queryParameters['with_status_info'] = opt_withStatusInfo;
  }

  /** @type {!Object} */
  var httpRequestParams = {
    method: 'GET',
    url: path,
    json: true,
            params: queryParameters,
    headers: headerParams
  };

  if (opt_extraHttpRequestParams) {
    httpRequestParams = angular.extend(httpRequestParams, opt_extraHttpRequestParams);
  }

  return (/** @type {?} */ (this.http_))(httpRequestParams);
}
