/**
 * FinFeedAPI Stock REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.20.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/OHLCV_TimeseriesItem.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

OHLCV_TimeseriesItem::OHLCV_TimeseriesItem()
{
    m_Time_period_start = utility::datetime();
    m_Time_period_startIsSet = false;
    m_Time_period_end = utility::datetime();
    m_Time_period_endIsSet = false;
    m_Volume_traded = 0.0;
    m_Volume_tradedIsSet = false;
    m_Trades_count = 0L;
    m_Trades_countIsSet = false;
}

OHLCV_TimeseriesItem::~OHLCV_TimeseriesItem()
{
}

void OHLCV_TimeseriesItem::validate()
{
    // TODO: implement validation
}

web::json::value OHLCV_TimeseriesItem::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Time_period_startIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("time_period_start"))] = ModelBase::toJson(m_Time_period_start);
    }
    if(m_Time_period_endIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("time_period_end"))] = ModelBase::toJson(m_Time_period_end);
    }
    if(m_Time_open.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("time_open"))] = ModelBase::toJson(m_Time_open.get());
    }
    if(m_Time_close.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("time_close"))] = ModelBase::toJson(m_Time_close.get());
    }
    if(m_Price_open.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("price_open"))] = ModelBase::toJson(m_Price_open.get());
    }
    if(m_Price_high.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("price_high"))] = ModelBase::toJson(m_Price_high.get());
    }
    if(m_Price_low.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("price_low"))] = ModelBase::toJson(m_Price_low.get());
    }
    if(m_Price_close.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("price_close"))] = ModelBase::toJson(m_Price_close.get());
    }
    if(m_Volume_tradedIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("volume_traded"))] = ModelBase::toJson(m_Volume_traded);
    }
    if(m_Trades_countIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("trades_count"))] = ModelBase::toJson(m_Trades_count);
    }

    return val;
}

bool OHLCV_TimeseriesItem::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("time_period_start"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("time_period_start")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setTimePeriodStart;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTimePeriodStart);
            setTimePeriodStart(refVal_setTimePeriodStart);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("time_period_end"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("time_period_end")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setTimePeriodEnd;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTimePeriodEnd);
            setTimePeriodEnd(refVal_setTimePeriodEnd);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("time_open"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("time_open")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setTimeOpen;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTimeOpen);
            setTimeOpen(refVal_setTimeOpen);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("time_close"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("time_close")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setTimeClose;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTimeClose);
            setTimeClose(refVal_setTimeClose);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("price_open"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("price_open")));
        if(!fieldValue.is_null())
        {
            double refVal_setPriceOpen;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPriceOpen);
            setPriceOpen(refVal_setPriceOpen);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("price_high"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("price_high")));
        if(!fieldValue.is_null())
        {
            double refVal_setPriceHigh;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPriceHigh);
            setPriceHigh(refVal_setPriceHigh);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("price_low"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("price_low")));
        if(!fieldValue.is_null())
        {
            double refVal_setPriceLow;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPriceLow);
            setPriceLow(refVal_setPriceLow);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("price_close"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("price_close")));
        if(!fieldValue.is_null())
        {
            double refVal_setPriceClose;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPriceClose);
            setPriceClose(refVal_setPriceClose);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("volume_traded"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("volume_traded")));
        if(!fieldValue.is_null())
        {
            double refVal_setVolumeTraded;
            ok &= ModelBase::fromJson(fieldValue, refVal_setVolumeTraded);
            setVolumeTraded(refVal_setVolumeTraded);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("trades_count"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("trades_count")));
        if(!fieldValue.is_null())
        {
            int64_t refVal_setTradesCount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTradesCount);
            setTradesCount(refVal_setTradesCount);
            
        }
    }
    return ok;
}

void OHLCV_TimeseriesItem::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Time_period_startIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("time_period_start")), m_Time_period_start));
    }
    if(m_Time_period_endIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("time_period_end")), m_Time_period_end));
    }
    if(m_Time_open.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("time_open")), m_Time_open.get()));
    }
    if(m_Time_close.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("time_close")), m_Time_close.get()));
    }
    if(m_Price_open.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("price_open")), m_Price_open.get()));
    }
    if(m_Price_high.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("price_high")), m_Price_high.get()));
    }
    if(m_Price_low.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("price_low")), m_Price_low.get()));
    }
    if(m_Price_close.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("price_close")), m_Price_close.get()));
    }
    if(m_Volume_tradedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("volume_traded")), m_Volume_traded));
    }
    if(m_Trades_countIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("trades_count")), m_Trades_count));
    }
}

bool OHLCV_TimeseriesItem::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("time_period_start"))))
    {
        utility::datetime refVal_setTimePeriodStart;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("time_period_start"))), refVal_setTimePeriodStart );
        setTimePeriodStart(refVal_setTimePeriodStart);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("time_period_end"))))
    {
        utility::datetime refVal_setTimePeriodEnd;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("time_period_end"))), refVal_setTimePeriodEnd );
        setTimePeriodEnd(refVal_setTimePeriodEnd);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("time_open"))))
    {
        utility::datetime refVal_setTimeOpen;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("time_open"))), refVal_setTimeOpen );
        setTimeOpen(refVal_setTimeOpen);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("time_close"))))
    {
        utility::datetime refVal_setTimeClose;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("time_close"))), refVal_setTimeClose );
        setTimeClose(refVal_setTimeClose);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("price_open"))))
    {
        double refVal_setPriceOpen;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("price_open"))), refVal_setPriceOpen );
        setPriceOpen(refVal_setPriceOpen);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("price_high"))))
    {
        double refVal_setPriceHigh;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("price_high"))), refVal_setPriceHigh );
        setPriceHigh(refVal_setPriceHigh);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("price_low"))))
    {
        double refVal_setPriceLow;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("price_low"))), refVal_setPriceLow );
        setPriceLow(refVal_setPriceLow);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("price_close"))))
    {
        double refVal_setPriceClose;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("price_close"))), refVal_setPriceClose );
        setPriceClose(refVal_setPriceClose);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("volume_traded"))))
    {
        double refVal_setVolumeTraded;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("volume_traded"))), refVal_setVolumeTraded );
        setVolumeTraded(refVal_setVolumeTraded);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("trades_count"))))
    {
        int64_t refVal_setTradesCount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("trades_count"))), refVal_setTradesCount );
        setTradesCount(refVal_setTradesCount);
    }
    return ok;
}


utility::datetime OHLCV_TimeseriesItem::getTimePeriodStart() const
{
    return m_Time_period_start;
}


void OHLCV_TimeseriesItem::setTimePeriodStart(const utility::datetime& value)
{
    m_Time_period_start = value;
    m_Time_period_startIsSet = true;
}

bool OHLCV_TimeseriesItem::timePeriodStartIsSet() const
{
    return m_Time_period_startIsSet;
}

void OHLCV_TimeseriesItem::unsetTime_period_start()
{
    m_Time_period_startIsSet = false;
}
utility::datetime OHLCV_TimeseriesItem::getTimePeriodEnd() const
{
    return m_Time_period_end;
}


void OHLCV_TimeseriesItem::setTimePeriodEnd(const utility::datetime& value)
{
    m_Time_period_end = value;
    m_Time_period_endIsSet = true;
}

bool OHLCV_TimeseriesItem::timePeriodEndIsSet() const
{
    return m_Time_period_endIsSet;
}

void OHLCV_TimeseriesItem::unsetTime_period_end()
{
    m_Time_period_endIsSet = false;
}
utility::datetime OHLCV_TimeseriesItem::getTimeOpen() const
{
    return m_Time_open.get();
}


void OHLCV_TimeseriesItem::setTimeOpen(const utility::datetime& value)
{
    m_Time_open = value;
}

bool OHLCV_TimeseriesItem::timeOpenIsSet() const
{
    return m_Time_open.has_value();
}

void OHLCV_TimeseriesItem::unsetTime_open()
{
    m_Time_open.reset();
}
utility::datetime OHLCV_TimeseriesItem::getTimeClose() const
{
    return m_Time_close.get();
}


void OHLCV_TimeseriesItem::setTimeClose(const utility::datetime& value)
{
    m_Time_close = value;
}

bool OHLCV_TimeseriesItem::timeCloseIsSet() const
{
    return m_Time_close.has_value();
}

void OHLCV_TimeseriesItem::unsetTime_close()
{
    m_Time_close.reset();
}
double OHLCV_TimeseriesItem::getPriceOpen() const
{
    return m_Price_open.get();
}

void OHLCV_TimeseriesItem::setPriceOpen(double value)
{
    m_Price_open = value;
}

bool OHLCV_TimeseriesItem::priceOpenIsSet() const
{
    return m_Price_open.has_value();
}

void OHLCV_TimeseriesItem::unsetPrice_open()
{
    m_Price_open.reset();
}
double OHLCV_TimeseriesItem::getPriceHigh() const
{
    return m_Price_high.get();
}

void OHLCV_TimeseriesItem::setPriceHigh(double value)
{
    m_Price_high = value;
}

bool OHLCV_TimeseriesItem::priceHighIsSet() const
{
    return m_Price_high.has_value();
}

void OHLCV_TimeseriesItem::unsetPrice_high()
{
    m_Price_high.reset();
}
double OHLCV_TimeseriesItem::getPriceLow() const
{
    return m_Price_low.get();
}

void OHLCV_TimeseriesItem::setPriceLow(double value)
{
    m_Price_low = value;
}

bool OHLCV_TimeseriesItem::priceLowIsSet() const
{
    return m_Price_low.has_value();
}

void OHLCV_TimeseriesItem::unsetPrice_low()
{
    m_Price_low.reset();
}
double OHLCV_TimeseriesItem::getPriceClose() const
{
    return m_Price_close.get();
}

void OHLCV_TimeseriesItem::setPriceClose(double value)
{
    m_Price_close = value;
}

bool OHLCV_TimeseriesItem::priceCloseIsSet() const
{
    return m_Price_close.has_value();
}

void OHLCV_TimeseriesItem::unsetPrice_close()
{
    m_Price_close.reset();
}
double OHLCV_TimeseriesItem::getVolumeTraded() const
{
    return m_Volume_traded;
}

void OHLCV_TimeseriesItem::setVolumeTraded(double value)
{
    m_Volume_traded = value;
    m_Volume_tradedIsSet = true;
}

bool OHLCV_TimeseriesItem::volumeTradedIsSet() const
{
    return m_Volume_tradedIsSet;
}

void OHLCV_TimeseriesItem::unsetVolume_traded()
{
    m_Volume_tradedIsSet = false;
}
int64_t OHLCV_TimeseriesItem::getTradesCount() const
{
    return m_Trades_count;
}

void OHLCV_TimeseriesItem::setTradesCount(int64_t value)
{
    m_Trades_count = value;
    m_Trades_countIsSet = true;
}

bool OHLCV_TimeseriesItem::tradesCountIsSet() const
{
    return m_Trades_countIsSet;
}

void OHLCV_TimeseriesItem::unsetTrades_count()
{
    m_Trades_countIsSet = false;
}

}
}
}
}


