# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MetricsV2Api")

api_instance <- MetricsV2Api$new()

test_that("MarketdataListMetricsV2AssetHistory", {
  # tests for MarketdataListMetricsV2AssetHistory
  # base path: https://rest.coinapi.io
  # Historical metrics for the asset
  # Get asset metrics history.
  # @param metric_id character Metric identifier (e.g., `TVL`, `STABLES_BRIDGED_USD`)
  # @param asset_id character Asset identifier (e.g., `USDC`, `USDT`)
  # @param time_start character Starting time in ISO 8601 (optional)
  # @param time_end character Ending time in ISO 8601 (optional)
  # @param time_format character If set, returned values will be in unix timestamp format (valid values: unix_sec, unix_millisec, unix_microsec, unix_nanosec) (optional)
  # @param period_id character Identifier of requested timeseries period (e.g. `1MIN` or `2MTH`), default value is `1MIN` (optional)
  # @param limit integer Amount of items to return (optional, mininum is 1, maximum is 100000, default value is 100, if the parameter is used then every 100 output items are counted as one request) (optional)
  # @return [array[object]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("MarketdataListMetricsV2AssetListing", {
  # tests for MarketdataListMetricsV2AssetListing
  # base path: https://rest.coinapi.io
  # Listing of metrics available for specific asset
  # Get all metrics that are actually available for the specified asset.
  # @param asset_id character Asset identifier (e.g., USDC, USDT)
  # @return [array[V1MetricInfo]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("MarketdataListMetricsV2ChainHistory", {
  # tests for MarketdataListMetricsV2ChainHistory
  # base path: https://rest.coinapi.io
  # Historical metrics for the chain
  # Get chain metrics history.
  # @param metric_id character Metric identifier (e.g., `TVL`, `STABLES_BRIDGED_USD`)
  # @param chain_id character Chain identifier (e.g., `Ethereum`, `Arbitrum`)
  # @param time_start character Starting time in ISO 8601 (optional)
  # @param time_end character Ending time in ISO 8601 (optional)
  # @param time_format character If set, returned values will be in unix timestamp format (valid values: unix_sec, unix_millisec, unix_microsec, unix_nanosec) (optional)
  # @param period_id character Identifier of requested timeseries period (e.g. `1MIN` or `2MTH`), default value is `1MIN` (optional)
  # @param limit integer Amount of items to return (optional, mininum is 1, maximum is 100000, default value is 100, if the parameter is used then every 100 output items are counted as one request) (optional)
  # @return [array[object]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("MarketdataListMetricsV2ChainListing", {
  # tests for MarketdataListMetricsV2ChainListing
  # base path: https://rest.coinapi.io
  # Listing of metrics available for specific chain
  # Get all metrics that are actually available for the specified blockchain chain.
  # @param chain_id character Chain identifier (e.g., ETHEREUM, ARBITRUM)
  # @return [array[V1MetricInfo]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("MarketdataListMetricsV2ExchangeHistory", {
  # tests for MarketdataListMetricsV2ExchangeHistory
  # base path: https://rest.coinapi.io
  # Historical metrics for the exchange
  # Get exchange metrics history.
  # @param metric_id character Metric identifier (e.g., `TVL`, `STABLES_BRIDGED_USD`)
  # @param exchange_id character Exchange identifier (e.g., `BINANCE`, `UNISWAP-V3-ETHEREUM`)
  # @param time_start character Starting time in ISO 8601 (optional)
  # @param time_end character Ending time in ISO 8601 (optional)
  # @param time_format character If set, returned values will be in unix timestamp format (valid values: unix_sec, unix_millisec, unix_microsec, unix_nanosec) (optional)
  # @param period_id character Identifier of requested timeseries period (e.g. `1MIN` or `2MTH`), default value is `1MIN` (optional)
  # @param limit integer Amount of items to return (optional, mininum is 1, maximum is 100000, default value is 100, if the parameter is used then every 100 output items are counted as one request) (optional)
  # @return [array[object]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("MarketdataListMetricsV2ExchangeListing", {
  # tests for MarketdataListMetricsV2ExchangeListing
  # base path: https://rest.coinapi.io
  # Listing of metrics available for specific exchange
  # Get all metrics that are actually available for the specified exchange.
  # @param exchange_id character Exchange identifier (e.g., BINANCE, UNISWAP-V3-ETHEREUM)
  # @return [array[V1MetricInfo]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("MarketdataListMetricsV2Listing", {
  # tests for MarketdataListMetricsV2Listing
  # base path: https://rest.coinapi.io
  # Listing of all supported metrics
  # Get all metrics available in the system.
  # @return [array[V1MetricInfo]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
