# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V1LastTrade")

model_instance <- V1LastTrade$new()

test_that("time_exchange", {
  # tests for the property `time_exchange` (character)
  # Gets or sets the exchange time of the last trade.

  # uncomment below to test the property
  #expect_equal(model.instance$`time_exchange`, "EXPECTED_RESULT")
})

test_that("time_coinapi", {
  # tests for the property `time_coinapi` (character)
  # Gets or sets the CoinAPI time when the last trade was received.

  # uncomment below to test the property
  #expect_equal(model.instance$`time_coinapi`, "EXPECTED_RESULT")
})

test_that("uuid", {
  # tests for the property `uuid` (character)
  # Gets or sets the UUID of the last trade.

  # uncomment below to test the property
  #expect_equal(model.instance$`uuid`, "EXPECTED_RESULT")
})

test_that("price", {
  # tests for the property `price` (numeric)
  # Gets or sets the price of the last trade.

  # uncomment below to test the property
  #expect_equal(model.instance$`price`, "EXPECTED_RESULT")
})

test_that("size", {
  # tests for the property `size` (numeric)
  # Gets or sets the size of the last trade.

  # uncomment below to test the property
  #expect_equal(model.instance$`size`, "EXPECTED_RESULT")
})

test_that("taker_side", {
  # tests for the property `taker_side` (character)
  # Gets or sets the taker side of the last trade.

  # uncomment below to test the property
  #expect_equal(model.instance$`taker_side`, "EXPECTED_RESULT")
})
