/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.V1LastTrade

class V1LastTradeTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of V1LastTrade
        //val modelInstance = V1LastTrade()

        // to test the property `timeExchange` - Gets or sets the exchange time of the last trade.
        should("test timeExchange") {
            // uncomment below to test the property
            //modelInstance.timeExchange shouldBe ("TODO")
        }

        // to test the property `timeCoinapi` - Gets or sets the CoinAPI time when the last trade was received.
        should("test timeCoinapi") {
            // uncomment below to test the property
            //modelInstance.timeCoinapi shouldBe ("TODO")
        }

        // to test the property `uuid` - Gets or sets the UUID of the last trade.
        should("test uuid") {
            // uncomment below to test the property
            //modelInstance.uuid shouldBe ("TODO")
        }

        // to test the property `price` - Gets or sets the price of the last trade.
        should("test price") {
            // uncomment below to test the property
            //modelInstance.price shouldBe ("TODO")
        }

        // to test the property `propertySize` - Gets or sets the size of the last trade.
        should("test propertySize") {
            // uncomment below to test the property
            //modelInstance.propertySize shouldBe ("TODO")
        }

        // to test the property `takerSide` - Gets or sets the taker side of the last trade.
        should("test takerSide") {
            // uncomment below to test the property
            //modelInstance.takerSide shouldBe ("TODO")
        }

    }
}
