/**
 * CoinAPI Market Data REST API
 * Cryptocurrency market data: metadata, quotes, books, trades, OHLCV, rates, metrics, options.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.time.OffsetDateTime
import java.util.UUID
import org.openapitools.client.core.ApiModel

case class LastTrade (
  /* Gets or sets the exchange time of the last trade. */
  timeExchange: Option[OffsetDateTime] = None,
  /* Gets or sets the CoinAPI time when the last trade was received. */
  timeCoinapi: Option[OffsetDateTime] = None,
  /* Gets or sets the UUID of the last trade. */
  uuid: Option[UUID] = None,
  /* Gets or sets the price of the last trade. */
  price: Option[Double] = None,
  /* Gets or sets the size of the last trade. */
  size: Option[Double] = None,
  /* Gets or sets the taker side of the last trade. */
  takerSide: Option[String] = None
) extends ApiModel

