/**
 * CoinAPI Market Data REST API
 * Cryptocurrency market data: metadata, quotes, books, trades, OHLCV, rates, metrics, options.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class Metric (
  /* Gets or sets the metric ID. */
  metricId: Option[String] = None,
  /* Gets or sets the metric description. */
  description: Option[String] = None
) extends ApiModel

