// @flow
/* eslint-disable no-use-before-define */
/**
 * CoinAPI Indexes REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as url from "url";
import * as portableFetch from "portable-fetch";
import { Configuration } from "./configuration";

const BASE_PATH: string = "https://rest-api.indexes.coinapi.io".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 */
export type FetchAPI = {
    (url: string, init?: any): Promise<Response>;
}

/**
 *
 * @export
 */
export type FetchArgs = {
    url: string;
    options: {};
}

/**
 *
 * @export
 */
export type RequestOptions = {
    headers?: {};
    query?: {};
    body?: string | FormData;
}

/**
 * * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name:string = "RequiredError"
    constructor(field: string, msg?: string) {
        super(msg);
    }
}

/**
 * 
 * @export
 */
export type ModelsIndexDefinitionSnapshotEntry = {
    /**
     * 
     * @type {string}
     * @memberof ModelsIndexDefinitionSnapshotEntry
     */
    index_id?: string;
    /**
     * 
     * @type {Date}
     * @memberof ModelsIndexDefinitionSnapshotEntry
     */
    timestamp?: Date;
    /**
     * 
     * @type {number}
     * @memberof ModelsIndexDefinitionSnapshotEntry
     */
    value?: number;
}

/**
 * Represents an index id
 * @export
 */
export type ModelsIndexIdentifier = {
    /**
     * Index ID
     * @type {string}
     * @memberof ModelsIndexIdentifier
     */
    id?: string;
}

/**
 * 
 * @export
 */
export type ModelsIndexMultiAssetWeight = {
    /**
     * 
     * @type {string}
     * @memberof ModelsIndexMultiAssetWeight
     */
    indexId?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsIndexMultiAssetWeight
     */
    assetId?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsIndexMultiAssetWeight
     */
    weight?: number;
}

/**
 * Represents a timeseries item with value information.
 * @export
 */
export type ModelsIndexTimeseriesItem = {
    /**
     * Gets or sets the start time of the time period.
     * @type {Date}
     * @memberof ModelsIndexTimeseriesItem
     */
    time_period_start?: Date;
    /**
     * Gets or sets the end time of the time period.
     * @type {Date}
     * @memberof ModelsIndexTimeseriesItem
     */
    time_period_end?: Date;
    /**
     * Gets or sets the time when the value opened.
     * @type {Date}
     * @memberof ModelsIndexTimeseriesItem
     */
    time_open?: Date;
    /**
     * Gets or sets the time when the value closed.
     * @type {Date}
     * @memberof ModelsIndexTimeseriesItem
     */
    time_close?: Date;
    /**
     * Gets or sets the opening value.
     * @type {number}
     * @memberof ModelsIndexTimeseriesItem
     */
    value_open?: number;
    /**
     * Gets or sets the highest value during the time period.
     * @type {number}
     * @memberof ModelsIndexTimeseriesItem
     */
    value_high?: number;
    /**
     * Gets or sets the lowest value during the time period.
     * @type {number}
     * @memberof ModelsIndexTimeseriesItem
     */
    value_low?: number;
    /**
     * Gets or sets the closing value.
     * @type {number}
     * @memberof ModelsIndexTimeseriesItem
     */
    value_close?: number;
    /**
     * Gets or sets the number of values during the time period.
     * @type {number}
     * @memberof ModelsIndexTimeseriesItem
     */
    value_count?: number;
}

/**
 * 
 * @export
 */
export type ModelsIndexValue = {
    /**
     * 
     * @type {Date}
     * @memberof ModelsIndexValue
     */
    timestamp?: Date;
    /**
     * 
     * @type {number}
     * @memberof ModelsIndexValue
     */
    value?: number;
    /**
     * 
     * @type {Array<ModelsIndexValueComponent>}
     * @memberof ModelsIndexValue
     */
    composition?: Array<ModelsIndexValueComponent>;
}

/**
 * 
 * @export
 */
export type ModelsIndexValueComponent = {
    /**
     * 
     * @type {string}
     * @memberof ModelsIndexValueComponent
     */
    component_id?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsIndexValueComponent
     */
    component_value?: number;
}



/**
 * IndexesApi - fetch parameter creator
 * @export
 */
export const IndexesApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get all multi-asset weights
         * @throws {RequiredError}
         */
        v1IndexdefMultiassetGet(options: RequestOptions): FetchArgs {
            const localVarPath = `/v1/indexdef/multiasset`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions: RequestOptions = Object.assign({}, { method: 'GET' }, options);
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};

            // authentication APIKey required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? configuration.apiKey("Authorization")
                    : configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            // authentication JWT required

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get multi-asset weights for specific index
         * @throws {RequiredError}
         */
        v1IndexdefMultiassetIndexIdGet(indexId: string, options: RequestOptions): FetchArgs {
            // verify required parameter 'indexId' is not null or undefined
            if (indexId === null || indexId === undefined) {
                throw new RequiredError('indexId','Required parameter indexId was null or undefined when calling v1IndexdefMultiassetIndexIdGet.');
            }
            const localVarPath = `/v1/indexdef/multiasset/{index_id}`
                .replace(`{${"index_id"}}`, encodeURIComponent(String(indexId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions: RequestOptions = Object.assign({}, { method: 'GET' }, options);
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};

            // authentication APIKey required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? configuration.apiKey("Authorization")
                    : configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            // authentication JWT required

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List indexes
         * @throws {RequiredError}
         */
        v1IndexesGet(options: RequestOptions): FetchArgs {
            const localVarPath = `/v1/indexes`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions: RequestOptions = Object.assign({}, { method: 'GET' }, options);
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};

            // authentication APIKey required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? configuration.apiKey("Authorization")
                    : configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            // authentication JWT required

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Current Index Values for index definition
         * @throws {RequiredError}
         */
        v1IndexesIndexDefinitionIdCurrentSnapshotGet(indexDefinitionId: string, options: RequestOptions): FetchArgs {
            // verify required parameter 'indexDefinitionId' is not null or undefined
            if (indexDefinitionId === null || indexDefinitionId === undefined) {
                throw new RequiredError('indexDefinitionId','Required parameter indexDefinitionId was null or undefined when calling v1IndexesIndexDefinitionIdCurrentSnapshotGet.');
            }
            const localVarPath = `/v1/indexes/{index_definition_id}/currentSnapshot`
                .replace(`{${"index_definition_id"}}`, encodeURIComponent(String(indexDefinitionId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions: RequestOptions = Object.assign({}, { method: 'GET' }, options);
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};

            // authentication APIKey required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? configuration.apiKey("Authorization")
                    : configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            // authentication JWT required

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Historical Index Values for index definition
         * @throws {RequiredError}
         */
        v1IndexesIndexDefinitionIdHistorySnapshotGet(indexDefinitionId: string, time?: Date, options: RequestOptions): FetchArgs {
            // verify required parameter 'indexDefinitionId' is not null or undefined
            if (indexDefinitionId === null || indexDefinitionId === undefined) {
                throw new RequiredError('indexDefinitionId','Required parameter indexDefinitionId was null or undefined when calling v1IndexesIndexDefinitionIdHistorySnapshotGet.');
            }
            const localVarPath = `/v1/indexes/{index_definition_id}/historySnapshot`
                .replace(`{${"index_definition_id"}}`, encodeURIComponent(String(indexDefinitionId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions: RequestOptions = Object.assign({}, { method: 'GET' }, options);
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};

            // authentication APIKey required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? configuration.apiKey("Authorization")
                    : configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            // authentication JWT required

            if (time !== undefined) {
                localVarQueryParameter['time'] = ((time:any):Date).toISOString();
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Current Index Value
         * @throws {RequiredError}
         */
        v1IndexesIndexIdCurrentGet(indexId: string, options: RequestOptions): FetchArgs {
            // verify required parameter 'indexId' is not null or undefined
            if (indexId === null || indexId === undefined) {
                throw new RequiredError('indexId','Required parameter indexId was null or undefined when calling v1IndexesIndexIdCurrentGet.');
            }
            const localVarPath = `/v1/indexes/{index_id}/current`
                .replace(`{${"index_id"}}`, encodeURIComponent(String(indexId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions: RequestOptions = Object.assign({}, { method: 'GET' }, options);
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};

            // authentication APIKey required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? configuration.apiKey("Authorization")
                    : configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            // authentication JWT required

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Historical Index Value w/Composition
         * @throws {RequiredError}
         */
        v1IndexesIndexIdHistoryGet(indexId: string, timeStart?: Date, timeEnd?: Date, limit?: number, options: RequestOptions): FetchArgs {
            // verify required parameter 'indexId' is not null or undefined
            if (indexId === null || indexId === undefined) {
                throw new RequiredError('indexId','Required parameter indexId was null or undefined when calling v1IndexesIndexIdHistoryGet.');
            }
            const localVarPath = `/v1/indexes/{index_id}/history`
                .replace(`{${"index_id"}}`, encodeURIComponent(String(indexId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions: RequestOptions = Object.assign({}, { method: 'GET' }, options);
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};

            // authentication APIKey required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? configuration.apiKey("Authorization")
                    : configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            // authentication JWT required

            if (timeStart !== undefined) {
                localVarQueryParameter['time_start'] = ((timeStart:any):Date).toISOString();
            }

            if (timeEnd !== undefined) {
                localVarQueryParameter['time_end'] = ((timeEnd:any):Date).toISOString();
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = ((limit:any):string);
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Timeseries Index Value
         * @throws {RequiredError}
         */
        v1IndexesIndexIdTimeseriesGet(indexId: string, periodId: string, timeStart: string, timeEnd: string, limit?: number, options: RequestOptions): FetchArgs {
            // verify required parameter 'indexId' is not null or undefined
            if (indexId === null || indexId === undefined) {
                throw new RequiredError('indexId','Required parameter indexId was null or undefined when calling v1IndexesIndexIdTimeseriesGet.');
            }
            // verify required parameter 'periodId' is not null or undefined
            if (periodId === null || periodId === undefined) {
                throw new RequiredError('periodId','Required parameter periodId was null or undefined when calling v1IndexesIndexIdTimeseriesGet.');
            }
            // verify required parameter 'timeStart' is not null or undefined
            if (timeStart === null || timeStart === undefined) {
                throw new RequiredError('timeStart','Required parameter timeStart was null or undefined when calling v1IndexesIndexIdTimeseriesGet.');
            }
            // verify required parameter 'timeEnd' is not null or undefined
            if (timeEnd === null || timeEnd === undefined) {
                throw new RequiredError('timeEnd','Required parameter timeEnd was null or undefined when calling v1IndexesIndexIdTimeseriesGet.');
            }
            const localVarPath = `/v1/indexes/{index_id}/timeseries`
                .replace(`{${"index_id"}}`, encodeURIComponent(String(indexId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions: RequestOptions = Object.assign({}, { method: 'GET' }, options);
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};

            // authentication APIKey required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? configuration.apiKey("Authorization")
                    : configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            // authentication JWT required

            if (periodId !== undefined) {
                localVarQueryParameter['period_id'] = ((periodId:any):string);
            }

            if (timeStart !== undefined) {
                localVarQueryParameter['time_start'] = ((timeStart:any):string);
            }

            if (timeEnd !== undefined) {
                localVarQueryParameter['time_end'] = ((timeEnd:any):string);
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = ((limit:any):string);
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

export type IndexesApiType = { 
    v1IndexdefMultiassetGet(options?: RequestOptions): Promise<Array<ModelsIndexMultiAssetWeight>>,

    v1IndexdefMultiassetIndexIdGet(indexId: string, options?: RequestOptions): Promise<Array<ModelsIndexMultiAssetWeight>>,

    v1IndexesGet(options?: RequestOptions): Promise<Array<ModelsIndexIdentifier>>,

    v1IndexesIndexDefinitionIdCurrentSnapshotGet(indexDefinitionId: string, options?: RequestOptions): Promise<Array<ModelsIndexDefinitionSnapshotEntry>>,

    v1IndexesIndexDefinitionIdHistorySnapshotGet(indexDefinitionId: string, time?: Date, options?: RequestOptions): Promise<Array<ModelsIndexDefinitionSnapshotEntry>>,

    v1IndexesIndexIdCurrentGet(indexId: string, options?: RequestOptions): Promise<ModelsIndexValue>,

    v1IndexesIndexIdHistoryGet(indexId: string, timeStart?: Date, timeEnd?: Date, limit?: number, options?: RequestOptions): Promise<Array<ModelsIndexValue>>,

    v1IndexesIndexIdTimeseriesGet(indexId: string, periodId: string, timeStart: string, timeEnd: string, limit?: number, options?: RequestOptions): Promise<Array<ModelsIndexTimeseriesItem>>,
}

/**
 * IndexesApi - factory function to inject configuration 
 * @export
 */
export const IndexesApi = function(configuration?: Configuration, fetch: FetchAPI = portableFetch): IndexesApiType {
    const basePath: string = (configuration && configuration.basePath) || BASE_PATH;
    return {
        /**
         * 
         * @summary Get all multi-asset weights
         * @throws {RequiredError}
         */
        v1IndexdefMultiassetGet(options?: RequestOptions = {}): Promise<Array<ModelsIndexMultiAssetWeight>> {
            const localVarFetchArgs = IndexesApiFetchParamCreator(configuration).v1IndexdefMultiassetGet(options);
            return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                if (response.status >= 200 && response.status < 300) {
                    return response.json();
                } else {
                    throw response;
                }
            });
        },
        /**
         * 
         * @summary Get multi-asset weights for specific index
         * @throws {RequiredError}
         */
        v1IndexdefMultiassetIndexIdGet(indexId: string, options?: RequestOptions = {}): Promise<Array<ModelsIndexMultiAssetWeight>> {
            const localVarFetchArgs = IndexesApiFetchParamCreator(configuration).v1IndexdefMultiassetIndexIdGet(indexId, options);
            return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                if (response.status >= 200 && response.status < 300) {
                    return response.json();
                } else {
                    throw response;
                }
            });
        },
        /**
         * 
         * @summary List indexes
         * @throws {RequiredError}
         */
        v1IndexesGet(options?: RequestOptions = {}): Promise<Array<ModelsIndexIdentifier>> {
            const localVarFetchArgs = IndexesApiFetchParamCreator(configuration).v1IndexesGet(options);
            return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                if (response.status >= 200 && response.status < 300) {
                    return response.json();
                } else {
                    throw response;
                }
            });
        },
        /**
         * 
         * @summary Current Index Values for index definition
         * @throws {RequiredError}
         */
        v1IndexesIndexDefinitionIdCurrentSnapshotGet(indexDefinitionId: string, options?: RequestOptions = {}): Promise<Array<ModelsIndexDefinitionSnapshotEntry>> {
            const localVarFetchArgs = IndexesApiFetchParamCreator(configuration).v1IndexesIndexDefinitionIdCurrentSnapshotGet(indexDefinitionId, options);
            return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                if (response.status >= 200 && response.status < 300) {
                    return response.json();
                } else {
                    throw response;
                }
            });
        },
        /**
         * 
         * @summary Historical Index Values for index definition
         * @throws {RequiredError}
         */
        v1IndexesIndexDefinitionIdHistorySnapshotGet(indexDefinitionId: string, time?: Date, options?: RequestOptions = {}): Promise<Array<ModelsIndexDefinitionSnapshotEntry>> {
            const localVarFetchArgs = IndexesApiFetchParamCreator(configuration).v1IndexesIndexDefinitionIdHistorySnapshotGet(indexDefinitionId, time, options);
            return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                if (response.status >= 200 && response.status < 300) {
                    return response.json();
                } else {
                    throw response;
                }
            });
        },
        /**
         * 
         * @summary Current Index Value
         * @throws {RequiredError}
         */
        v1IndexesIndexIdCurrentGet(indexId: string, options?: RequestOptions = {}): Promise<ModelsIndexValue> {
            const localVarFetchArgs = IndexesApiFetchParamCreator(configuration).v1IndexesIndexIdCurrentGet(indexId, options);
            return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                if (response.status >= 200 && response.status < 300) {
                    return response.json();
                } else {
                    throw response;
                }
            });
        },
        /**
         * 
         * @summary Historical Index Value w/Composition
         * @throws {RequiredError}
         */
        v1IndexesIndexIdHistoryGet(indexId: string, timeStart?: Date, timeEnd?: Date, limit?: number, options?: RequestOptions = {}): Promise<Array<ModelsIndexValue>> {
            const localVarFetchArgs = IndexesApiFetchParamCreator(configuration).v1IndexesIndexIdHistoryGet(indexId, timeStart, timeEnd, limit, options);
            return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                if (response.status >= 200 && response.status < 300) {
                    return response.json();
                } else {
                    throw response;
                }
            });
        },
        /**
         * 
         * @summary Timeseries Index Value
         * @throws {RequiredError}
         */
        v1IndexesIndexIdTimeseriesGet(indexId: string, periodId: string, timeStart: string, timeEnd: string, limit?: number, options?: RequestOptions = {}): Promise<Array<ModelsIndexTimeseriesItem>> {
            const localVarFetchArgs = IndexesApiFetchParamCreator(configuration).v1IndexesIndexIdTimeseriesGet(indexId, periodId, timeStart, timeEnd, limit, options);
            return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                if (response.status >= 200 && response.status < 300) {
                    return response.json();
                } else {
                    throw response;
                }
            });
        },
    }
};


export type ApiTypes = { 
    IndexesApi: IndexesApiType,
 }
