--[[
  CoinAPI Market Data REST API

  Cryptocurrency market data: metadata, quotes, books, trades, OHLCV, rates, metrics, options.

  The version of the OpenAPI document: v1
  Contact: support@apibricks.io
  Generated by: https://openapi-generator.tech
]]

-- v1_symbol_mapping class
local v1_symbol_mapping = {}
local v1_symbol_mapping_mt = {
	__name = "v1_symbol_mapping";
	__index = v1_symbol_mapping;
}

local function cast_v1_symbol_mapping(t)
	return setmetatable(t, v1_symbol_mapping_mt)
end

local function new_v1_symbol_mapping(symbol_id, symbol_id_exchange, coinapi_datainfo_id, asset_id_base_exchange, asset_id_quote_exchange, asset_id_base, asset_id_quote, price_precision, size_precision)
	return cast_v1_symbol_mapping({
		["symbol_id"] = symbol_id;
		["symbol_id_exchange"] = symbol_id_exchange;
		["coinapi_datainfo_id"] = coinapi_datainfo_id;
		["asset_id_base_exchange"] = asset_id_base_exchange;
		["asset_id_quote_exchange"] = asset_id_quote_exchange;
		["asset_id_base"] = asset_id_base;
		["asset_id_quote"] = asset_id_quote;
		["price_precision"] = price_precision;
		["size_precision"] = size_precision;
	})
end

return {
	cast = cast_v1_symbol_mapping;
	new = new_v1_symbol_mapping;
}
